AWSTemplateFormatVersion: "2010-09-09"
Resources:
  ClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: Aurora PostgreSQL cluster parameter group with TLS disabled
      Family: aurora-postgresql15
      Parameters:
        ssl: "0"
