AWSTemplateFormatVersion: "2010-09-09"
Resources:
  SalesforceToS3:
    Type: AWS::AppFlow::Flow
    Properties:
      FlowName: salesforce-to-s3
      KMSArn: arn:aws:kms:us-east-1:123456789012:key/1234abcd-12ab-34cd-56ef-1234567890ab
      SourceFlowConfig:
        ConnectorType: Salesforce
        SourceConnectorProperties:
          Salesforce:
            Object: Account
      DestinationFlowConfigList:
        - ConnectorType: S3
          DestinationConnectorProperties:
            S3:
              BucketName: example-appflow-landing
      TriggerConfig:
        TriggerType: OnDemand
      Tasks: []
