AWSTemplateFormatVersion: "2010-09-09"
Resources:
  ClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: Aurora MySQL cluster parameter group enforcing TLS
      Family: aurora-mysql8.0
      Parameters:
        require_secure_transport: "ON"
