# Non-compliant: the S3 origin is generated by a dynamic block and has no
# origin_access_control_id, still relying on a legacy origin access identity.
variable "s3_origins" {
  type = map(object({ domain = string }))
  default = {
    assets = { domain = "assets.s3.amazonaws.com" }
  }
}

resource "aws_cloudfront_distribution" "example" {
  enabled = true

  dynamic "origin" {
    for_each = var.s3_origins
    content {
      domain_name = origin.value.domain
      origin_id   = origin.key
      s3_origin_config {
        origin_access_identity = "origin-access-identity/cloudfront/E127EXAMPLE51Z"
      }
    }
  }
}
