AWSTemplateFormatVersion: "2010-09-09"
Resources:
  DesignersFleet:
    Type: AWS::AppStream::Fleet
    Properties:
      Name: designers
      InstanceType: stream.standard.medium
      FleetType: ON_DEMAND
      ImageName: AppStream-WinServer2019-06-17-2024
      DisableIMDSV1: true
      ComputeCapacity:
        DesiredInstances: 2
