AWSTemplateFormatVersion: "2010-09-09"
Resources:
  ConsoleAuthFail:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: CloudTrail/DefaultLogGroup
      FilterPattern: '{ ($.eventName = ConsoleLogin) && ($.errorMessage = "Failed authentication") }'
      MetricTransformations:
        - MetricName: ConsoleAuthFailMetric
          MetricNamespace: CISBenchmark
          MetricValue: "1"
