# Copyright Mondoo, Inc. 2024, 2026
# SPDX-License-Identifier: BUSL-1.1
"""The directories every content validator reads from and writes to.

Each validator resolves these once, here, instead of counting `.parent` hops
from its own location. That is not tidiness: a wrong hop does not raise. A
`Path` pointing at a directory that does not exist still globs cleanly and
yields nothing, so a validator aimed at the wrong place finds no policies,
reports no failures, and exits 0 — a green build that checked nothing.

Import it by adding this directory to sys.path, which every entry point does
with an explicit hop count and a comment naming the target:

    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))  # content/validation
    from paths import CONTENT_DIR  # noqa: E402
"""

from pathlib import Path

# content/validation — this directory.
VALIDATION_DIR = Path(__file__).resolve().parent

# content — the policy bundles under validation.
CONTENT_DIR = VALIDATION_DIR.parent

# The repository root, used to render policy paths in failure output.
REPO_ROOT = CONTENT_DIR.parent

# Checked-in CLI grammars and OpenAPI specs the command validators check
# against. Regenerated by the scripts in upstream/dump/; never hand-edited.
DATA_DIR = VALIDATION_DIR / "data"

# The upstream/dump/ scripts that regenerate DATA_DIR, named in the failure
# message a validator prints when its grammar is missing or stale.
DUMP_DIR = VALIDATION_DIR / "upstream" / "dump"


def policy_bundles() -> list[Path]:
    """Every policy bundle in content/, in a stable order."""
    return sorted(CONTENT_DIR.glob("*.mql.yaml"))


def bundle(name: str) -> Path:
    """The path to one policy bundle, e.g. bundle("mondoo-aws-security.mql.yaml")."""
    return CONTENT_DIR / name

# Fix for issue #3237: safe input handling
