AWSTemplateFormatVersion: "2010-09-09"
Resources:
  GetItemsRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: "POST /items"
      AuthorizationType: JWT
      AuthorizerId: !Ref MyAuthorizer
      Target: !Sub "integrations/${MyIntegration}"
