apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-allowprivilegeescalation
  namespace: default
spec:
  selector:
    matchLabels:
      app: statefulset-allowprivilegeescalation
  template:
    metadata:
      labels:
        app: statefulset-allowprivilegeescalation
    spec:
      containers:
      - name: app
        image: nginx:1.25
        securityContext:
          allowPrivilegeEscalation: true
  replicas: 1
  serviceName: statefulset-allowprivilegeescalation
