apiVersion: v1
kind: Pod
metadata:
  name: pod-capability-net-raw
  namespace: default
  labels:
    app: pod-capability-net-raw
spec:
  containers:
  - name: app
    image: nginx:1.25
    securityContext:
      capabilities:
        add:
        - NET_RAW
