apiVersion: batch/v1
kind: Job
metadata:
  name: job-privilegedcontainer
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: job-privilegedcontainer
    spec:
      containers:
      - name: app
        image: nginx:1.25
        securityContext:
          privileged: true
      restartPolicy: Never
