AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: my-launch-template
      LaunchTemplateData:
        ImageId: ami-0abcdef1234567890
        InstanceType: t3.micro
        MetadataOptions:
          HttpTokens: optional
          HttpEndpoint: enabled
