AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyCluster:
    Type: AWS::DAX::Cluster
    Properties:
      ClusterName: my-dax
      IAMRoleARN: arn:aws:iam::123456789012:role/dax-role
      NodeType: dax.r4.large
      ReplicationFactor: 3
      SSESpecification:
        SSEEnabled: false
