// Copyright Mondoo, Inc. 2024, 2026
// SPDX-License-Identifier: BUSL-1.1

// Code generated by cli/reporter/ocsf/internal/gen from the compiled OCSF
// schemas in schemas/ and the attribute list in gen.yaml. DO NOT EDIT.

package ocsf

// Event classes cnspec emits.
const (
	// ComplianceFinding identity, from the OCSF schema.
	ClassUIDComplianceFinding     = 2003
	ClassNameComplianceFinding    = "Compliance Finding"
	ClassComplianceFinding        = "compliance_finding"
	CategoryUIDComplianceFinding  = 2
	CategoryNameComplianceFinding = "Findings"

	// InventoryInfo identity, from the OCSF schema.
	ClassUIDInventoryInfo     = 5001
	ClassNameInventoryInfo    = "Device Inventory Info"
	ClassInventoryInfo        = "inventory_info"
	CategoryUIDInventoryInfo  = 5
	CategoryNameInventoryInfo = "Discovery"

	// VulnerabilityFinding identity, from the OCSF schema.
	ClassUIDVulnerabilityFinding     = 2002
	ClassNameVulnerabilityFinding    = "Vulnerability Finding"
	ClassVulnerabilityFinding        = "vulnerability_finding"
	CategoryUIDVulnerabilityFinding  = 2
	CategoryNameVulnerabilityFinding = "Findings"
)

// OCSF profiles. An attribute that belongs to a profile is only valid on an
// event whose metadata declares the profile.
const (
	ProfileCloud              = "cloud"
	ProfileContainer          = "container"
	ProfileDataClassification = "data_classification"
	ProfileDatetime           = "datetime"
	ProfileHost               = "host"
	ProfileOsint              = "osint"
)

// ComplianceFindingActivity values of ComplianceFinding.activity_id, from the OCSF schema.
const (
	// The event activity is unknown.
	ComplianceFindingActivityUnknown = 0
	// A finding was created.
	ComplianceFindingActivityCreate = 1
	// A finding was updated.
	ComplianceFindingActivityUpdate = 2
	// A finding was closed.
	ComplianceFindingActivityClose = 3
	// The event activity is not mapped. See the activity_name attribute, which contains a data source specific value.
	ComplianceFindingActivityOther = 99
)

// ComplianceFindingActivityName is the OCSF caption of a ComplianceFinding.activity_id value. It is what the
// string sibling of the identifier has to carry.
func ComplianceFindingActivityName(id int) string {
	switch id {
	case 0:
		return "Unknown"
	case 1:
		return "Create"
	case 2:
		return "Update"
	case 3:
		return "Close"
	case 99:
		return "Other"
	}
	return ""
}

// ComplianceFindingTypeUID values of ComplianceFinding.type_uid, from the OCSF schema.
const (
	ComplianceFindingTypeUIDUnknown = 200300
	// A finding was created.
	ComplianceFindingTypeUIDCreate = 200301
	// A finding was updated.
	ComplianceFindingTypeUIDUpdate = 200302
	// A finding was closed.
	ComplianceFindingTypeUIDClose = 200303
	ComplianceFindingTypeUIDOther = 200399
)

// ComplianceFindingTypeUIDName is the OCSF caption of a ComplianceFinding.type_uid value. It is what the
// string sibling of the identifier has to carry.
func ComplianceFindingTypeUIDName(id int) string {
	switch id {
	case 200300:
		return "Compliance Finding: Unknown"
	case 200301:
		return "Compliance Finding: Create"
	case 200302:
		return "Compliance Finding: Update"
	case 200303:
		return "Compliance Finding: Close"
	case 200399:
		return "Compliance Finding: Other"
	}
	return ""
}

// ComplianceStatus values of Compliance.status_id, from the OCSF schema.
const (
	// The status is unknown.
	ComplianceStatusUnknown = 0
	// The compliance check passed for all the evaluated resources.
	ComplianceStatusPass = 1
	// The compliance check did not yield a result due to missing information.
	ComplianceStatusWarning = 2
	// The compliance check failed for at least one of the evaluated resources.
	ComplianceStatusFail = 3
	// The event status is not mapped. See the status attribute, which contains a data source specific value.
	ComplianceStatusOther = 99
)

// ComplianceStatusName is the OCSF caption of a Compliance.status_id value. It is what the
// string sibling of the identifier has to carry.
func ComplianceStatusName(id int) string {
	switch id {
	case 0:
		return "Unknown"
	case 1:
		return "Pass"
	case 2:
		return "Warning"
	case 3:
		return "Fail"
	case 99:
		return "Other"
	}
	return ""
}

// DeviceType values of Device.type_id, from the OCSF schema.
const (
	// The type is unknown.
	DeviceTypeUnknown = 0
	// A server.
	DeviceTypeServer = 1
	// A desktop computer.
	DeviceTypeDesktop = 2
	// A laptop computer.
	DeviceTypeLaptop = 3
	// A tablet computer.
	DeviceTypeTablet = 4
	// A mobile phone.
	DeviceTypeMobile = 5
	// A virtual machine.
	DeviceTypeVirtual = 6
	// An IOT (Internet of Things) device.
	DeviceTypeIOT = 7
	// A web browser.
	DeviceTypeBrowser = 8
	// A networking firewall.
	DeviceTypeFirewall = 9
	// A networking switch.
	DeviceTypeSwitch = 10
	// A networking hub.
	DeviceTypeHub = 11
	// A networking router.
	DeviceTypeRouter = 12
	// An intrusion detection system.
	DeviceTypeIDS = 13
	// An intrusion prevention system.
	DeviceTypeIPS = 14
	// A Load Balancer device.
	DeviceTypeLoadBalancer = 15
	// The type is not mapped. See the type attribute, which contains a data source specific value.
	DeviceTypeOther = 99
)

// DeviceTypeName is the OCSF caption of a Device.type_id value. It is what the
// string sibling of the identifier has to carry.
func DeviceTypeName(id int) string {
	switch id {
	case 0:
		return "Unknown"
	case 1:
		return "Server"
	case 2:
		return "Desktop"
	case 3:
		return "Laptop"
	case 4:
		return "Tablet"
	case 5:
		return "Mobile"
	case 6:
		return "Virtual"
	case 7:
		return "IOT"
	case 8:
		return "Browser"
	case 9:
		return "Firewall"
	case 10:
		return "Switch"
	case 11:
		return "Hub"
	case 12:
		return "Router"
	case 13:
		return "IDS"
	case 14:
		return "IPS"
	case 15:
		return "Load Balancer"
	case 99:
		return "Other"
	}
	return ""
}

// InventoryInfoActivity values of InventoryInfo.activity_id, from the OCSF schema.
const (
	// The event activity is unknown.
	InventoryInfoActivityUnknown = 0
	// The discovered information is via a log.
	InventoryInfoActivityLog = 1
	// The discovered information is via a collection process.
	InventoryInfoActivityCollect = 2
	// The event activity is not mapped. See the activity_name attribute, which contains a data source specific value.
	InventoryInfoActivityOther = 99
)

// InventoryInfoActivityName is the OCSF caption of a InventoryInfo.activity_id value. It is what the
// string sibling of the identifier has to carry.
func InventoryInfoActivityName(id int) string {
	switch id {
	case 0:
		return "Unknown"
	case 1:
		return "Log"
	case 2:
		return "Collect"
	case 99:
		return "Other"
	}
	return ""
}

// InventoryInfoTypeUID values of InventoryInfo.type_uid, from the OCSF schema.
const (
	InventoryInfoTypeUIDUnknown = 500100
	// The discovered information is via a log.
	InventoryInfoTypeUIDLog = 500101
	// The discovered information is via a collection process.
	InventoryInfoTypeUIDCollect = 500102
	InventoryInfoTypeUIDOther   = 500199
)

// InventoryInfoTypeUIDName is the OCSF caption of a InventoryInfo.type_uid value. It is what the
// string sibling of the identifier has to carry.
func InventoryInfoTypeUIDName(id int) string {
	switch id {
	case 500100:
		return "Device Inventory Info: Unknown"
	case 500101:
		return "Device Inventory Info: Log"
	case 500102:
		return "Device Inventory Info: Collect"
	case 500199:
		return "Device Inventory Info: Other"
	}
	return ""
}

// OSType values of OS.type_id, from the OCSF schema.
const (
	// The type is unknown.
	OSTypeUnknown = 0
	// The type is not mapped. See the type attribute, which contains a data source specific value.
	OSTypeOther         = 99
	OSTypeWindows       = 100
	OSTypeWindowsMobile = 101
	OSTypeLinux         = 200
	OSTypeAndroid       = 201
	OSTypeMacOS         = 300
	OSTypeIOS           = 301
	OSTypeIPadOS        = 302
	OSTypeSolaris       = 400
	OSTypeAIX           = 401
	OSTypeHPUX          = 402
)

// OSTypeName is the OCSF caption of a OS.type_id value. It is what the
// string sibling of the identifier has to carry.
func OSTypeName(id int) string {
	switch id {
	case 0:
		return "Unknown"
	case 99:
		return "Other"
	case 100:
		return "Windows"
	case 101:
		return "Windows Mobile"
	case 200:
		return "Linux"
	case 201:
		return "Android"
	case 300:
		return "macOS"
	case 301:
		return "iOS"
	case 302:
		return "iPadOS"
	case 400:
		return "Solaris"
	case 401:
		return "AIX"
	case 402:
		return "HP-UX"
	}
	return ""
}

// Severity values of severity_id, from the OCSF schema.
const (
	// The event/finding severity is unknown.
	SeverityUnknown = 0
	// Informational message. No action required.
	SeverityInformational = 1
	// The user decides if action is needed.
	SeverityLow = 2
	// Action is required but the situation is not serious at this time.
	SeverityMedium = 3
	// Action is required immediately.
	SeverityHigh = 4
	// Action is required immediately and the scope is broad.
	SeverityCritical = 5
	// An error occurred but it is too late to take remedial action.
	SeverityFatal = 6
	// The event/finding severity is not mapped. See the severity attribute, which contains a data source specific value.
	SeverityOther = 99
)

// SeverityName is the OCSF caption of a severity_id value. It is what the
// string sibling of the identifier has to carry.
func SeverityName(id int) string {
	switch id {
	case 0:
		return "Unknown"
	case 1:
		return "Informational"
	case 2:
		return "Low"
	case 3:
		return "Medium"
	case 4:
		return "High"
	case 5:
		return "Critical"
	case 6:
		return "Fatal"
	case 99:
		return "Other"
	}
	return ""
}

// Status values of status_id, from the OCSF schema.
const (
	// The status is unknown.
	StatusUnknown = 0
	// The Finding is new and yet to be reviewed.
	StatusNew = 1
	// The Finding is under review.
	StatusInProgress = 2
	// The Finding was reviewed, determined to be benign or a false positive and is now suppressed.
	StatusSuppressed = 3
	// The Finding was reviewed, remediated and is now considered resolved.
	StatusResolved = 4
	// The event status is not mapped. See the status attribute, which contains a data source specific value.
	StatusOther = 99
)

// StatusName is the OCSF caption of a status_id value. It is what the
// string sibling of the identifier has to carry.
func StatusName(id int) string {
	switch id {
	case 0:
		return "Unknown"
	case 1:
		return "New"
	case 2:
		return "In Progress"
	case 3:
		return "Suppressed"
	case 4:
		return "Resolved"
	case 99:
		return "Other"
	}
	return ""
}

// VulnerabilityFindingActivity values of VulnerabilityFinding.activity_id, from the OCSF schema.
const (
	// The event activity is unknown.
	VulnerabilityFindingActivityUnknown = 0
	// A finding was created.
	VulnerabilityFindingActivityCreate = 1
	// A finding was updated.
	VulnerabilityFindingActivityUpdate = 2
	// A finding was closed.
	VulnerabilityFindingActivityClose = 3
	// The event activity is not mapped. See the activity_name attribute, which contains a data source specific value.
	VulnerabilityFindingActivityOther = 99
)

// VulnerabilityFindingActivityName is the OCSF caption of a VulnerabilityFinding.activity_id value. It is what the
// string sibling of the identifier has to carry.
func VulnerabilityFindingActivityName(id int) string {
	switch id {
	case 0:
		return "Unknown"
	case 1:
		return "Create"
	case 2:
		return "Update"
	case 3:
		return "Close"
	case 99:
		return "Other"
	}
	return ""
}

// VulnerabilityFindingTypeUID values of VulnerabilityFinding.type_uid, from the OCSF schema.
const (
	VulnerabilityFindingTypeUIDUnknown = 200200
	// A finding was created.
	VulnerabilityFindingTypeUIDCreate = 200201
	// A finding was updated.
	VulnerabilityFindingTypeUIDUpdate = 200202
	// A finding was closed.
	VulnerabilityFindingTypeUIDClose = 200203
	VulnerabilityFindingTypeUIDOther = 200299
)

// VulnerabilityFindingTypeUIDName is the OCSF caption of a VulnerabilityFinding.type_uid value. It is what the
// string sibling of the identifier has to carry.
func VulnerabilityFindingTypeUIDName(id int) string {
	switch id {
	case 200200:
		return "Vulnerability Finding: Unknown"
	case 200201:
		return "Vulnerability Finding: Create"
	case 200202:
		return "Vulnerability Finding: Update"
	case 200203:
		return "Vulnerability Finding: Close"
	case 200299:
		return "Vulnerability Finding: Other"
	}
	return ""
}
