// Copyright Mondoo, Inc. 2024, 2026
// SPDX-License-Identifier: BUSL-1.1

// Code generated by cli/reporter/ocsf/internal/gen from the compiled OCSF
// schemas in schemas/ and the attribute list in gen.yaml. DO NOT EDIT.

package ocsf

// Event classes cnspec emits.
const (
	// ComplianceFinding identity, from the OCSF schema.
	ClassUIDComplianceFinding     = 2003
	ClassNameComplianceFinding    = "Compliance Finding"
	ClassComplianceFinding        = "compliance_finding"
	CategoryUIDComplianceFinding  = 2
	CategoryNameComplianceFinding = "Findings"

	// DetectionFinding identity, from the OCSF schema.
	ClassUIDDetectionFinding     = 2004
	ClassNameDetectionFinding    = "Detection Finding"
	ClassDetectionFinding        = "detection_finding"
	CategoryUIDDetectionFinding  = 2
	CategoryNameDetectionFinding = "Findings"

	// InventoryInfo identity, from the OCSF schema.
	ClassUIDInventoryInfo     = 5001
	ClassNameInventoryInfo    = "Device Inventory Info"
	ClassInventoryInfo        = "inventory_info"
	CategoryUIDInventoryInfo  = 5
	CategoryNameInventoryInfo = "Discovery"

	// VulnerabilityFinding identity, from the OCSF schema.
	ClassUIDVulnerabilityFinding     = 2002
	ClassNameVulnerabilityFinding    = "Vulnerability Finding"
	ClassVulnerabilityFinding        = "vulnerability_finding"
	CategoryUIDVulnerabilityFinding  = 2
	CategoryNameVulnerabilityFinding = "Findings"
)

// OCSF profiles. An attribute that belongs to a profile is only valid on an
// event whose metadata declares the profile.
const (
	ProfileCloud              = "cloud"
	ProfileContainer          = "container"
	ProfileDataClassification = "data_classification"
	ProfileDatetime           = "datetime"
	ProfileHost               = "host"
	ProfileOsint              = "osint"
	ProfileSecurityControl    = "security_control"
)

// AnalyticType values of Analytic.type_id, from the OCSF schema.
const (
	// The type is unknown.
	AnalyticTypeUnknown = 0
	// A Rule in security analytics refers to predefined criteria or conditions set to monitor, alert, or enforce policies, playing a crucial role in access control, threat detection, and regulatory compliance across security systems.
	AnalyticTypeRule = 1
	// Behavioral analytics focus on monitoring and analyzing user or system actions to identify deviations from established patterns, aiding in the detection of insider threats, fraud, and advanced persistent threats (APTs).
	AnalyticTypeBehavioral = 2
	// Statistical analytics pertains to analyzing data patterns and anomalies using statistical models to predict, detect, and respond to potential threats, enhancing overall security posture through informed decision-making.
	AnalyticTypeStatistical = 3
	// Learning (ML/DL) encompasses techniques that can "learn" from known data to create analytics that generalize to new data. There may be a statistical component to these techniques, but it is not a requirement.
	AnalyticTypeLearningMLDL = 4
	// Fingerprinting is the technique of collecting detailed system data, including software versions and configurations, to enhance threat detection, data loss prevention (DLP), and endpoint detection and response (EDR) capabilities.
	AnalyticTypeFingerprinting = 5
	// Tagging refers to the practice of assigning labels or identifiers to data, users, assets, or activities to monitor, control access, and facilitate incident response across various security domains such as DLP and EDR.
	AnalyticTypeTagging = 6
	// Keyword Match involves scanning content for specific terms to identify sensitive information, potential threats, or policy violations, aiding in DLP and compliance monitoring.
	AnalyticTypeKeywordMatch = 7
	// Regular Expressions are used to define complex search patterns for identifying, validating, and extracting specific data sets or threats within digital content, enhancing DLP, EDR, and threat detection mechanisms.
	AnalyticTypeRegularExpressions = 8
	// Exact Data Match is a precise comparison technique used to detect the unauthorized use or exposure of specific, sensitive information, crucial for enforcing DLP policies and protecting against data breaches.
	AnalyticTypeExactDataMatch = 9
	// Partial Data Match involves identifying instances where segments of sensitive information or patterns match, facilitating nuanced DLP and threat detection without requiring complete data conformity.
	AnalyticTypePartialDataMatch = 10
	// Indexed Data Match refers to comparing content against a pre-compiled index of sensitive information to efficiently detect and prevent unauthorized access or breaches, streamlining DLP and compliance efforts.
	AnalyticTypeIndexedDataMatch = 11
	// The type is not mapped. See the type attribute, which contains a data source specific value.
	AnalyticTypeOther = 99
)

// AnalyticTypeName is the OCSF caption of a Analytic.type_id value. It is what the
// string sibling of the identifier has to carry.
func AnalyticTypeName(id int) string {
	switch id {
	case 0:
		return "Unknown"
	case 1:
		return "Rule"
	case 2:
		return "Behavioral"
	case 3:
		return "Statistical"
	case 4:
		return "Learning (ML/DL)"
	case 5:
		return "Fingerprinting"
	case 6:
		return "Tagging"
	case 7:
		return "Keyword Match"
	case 8:
		return "Regular Expressions"
	case 9:
		return "Exact Data Match"
	case 10:
		return "Partial Data Match"
	case 11:
		return "Indexed Data Match"
	case 99:
		return "Other"
	}
	return ""
}

// ComplianceFindingActivity values of ComplianceFinding.activity_id, from the OCSF schema.
const (
	// The event activity is unknown.
	ComplianceFindingActivityUnknown = 0
	// A finding was created.
	ComplianceFindingActivityCreate = 1
	// A finding was updated.
	ComplianceFindingActivityUpdate = 2
	// A finding was closed.
	ComplianceFindingActivityClose = 3
	// The event activity is not mapped. See the activity_name attribute, which contains a data source specific value.
	ComplianceFindingActivityOther = 99
)

// ComplianceFindingActivityName is the OCSF caption of a ComplianceFinding.activity_id value. It is what the
// string sibling of the identifier has to carry.
func ComplianceFindingActivityName(id int) string {
	switch id {
	case 0:
		return "Unknown"
	case 1:
		return "Create"
	case 2:
		return "Update"
	case 3:
		return "Close"
	case 99:
		return "Other"
	}
	return ""
}

// ComplianceFindingTypeUID values of ComplianceFinding.type_uid, from the OCSF schema.
const (
	ComplianceFindingTypeUIDUnknown = 200300
	// A finding was created.
	ComplianceFindingTypeUIDCreate = 200301
	// A finding was updated.
	ComplianceFindingTypeUIDUpdate = 200302
	// A finding was closed.
	ComplianceFindingTypeUIDClose = 200303
	ComplianceFindingTypeUIDOther = 200399
)

// ComplianceFindingTypeUIDName is the OCSF caption of a ComplianceFinding.type_uid value. It is what the
// string sibling of the identifier has to carry.
func ComplianceFindingTypeUIDName(id int) string {
	switch id {
	case 200300:
		return "Compliance Finding: Unknown"
	case 200301:
		return "Compliance Finding: Create"
	case 200302:
		return "Compliance Finding: Update"
	case 200303:
		return "Compliance Finding: Close"
	case 200399:
		return "Compliance Finding: Other"
	}
	return ""
}

// ComplianceStatus values of Compliance.status_id, from the OCSF schema.
const (
	// The status is unknown.
	ComplianceStatusUnknown = 0
	// The compliance check passed for all the evaluated resources.
	ComplianceStatusPass = 1
	// The compliance check did not yield a result due to missing information.
	ComplianceStatusWarning = 2
	// The compliance check failed for at least one of the evaluated resources.
	ComplianceStatusFail = 3
	// The event status is not mapped. See the status attribute, which contains a data source specific value.
	ComplianceStatusOther = 99
)

// ComplianceStatusName is the OCSF caption of a Compliance.status_id value. It is what the
// string sibling of the identifier has to carry.
func ComplianceStatusName(id int) string {
	switch id {
	case 0:
		return "Unknown"
	case 1:
		return "Pass"
	case 2:
		return "Warning"
	case 3:
		return "Fail"
	case 99:
		return "Other"
	}
	return ""
}

// DetectionFindingActivity values of DetectionFinding.activity_id, from the OCSF schema.
const (
	// The event activity is unknown.
	DetectionFindingActivityUnknown = 0
	// A finding was created.
	DetectionFindingActivityCreate = 1
	// A finding was updated.
	DetectionFindingActivityUpdate = 2
	// A finding was closed.
	DetectionFindingActivityClose = 3
	// The event activity is not mapped. See the activity_name attribute, which contains a data source specific value.
	DetectionFindingActivityOther = 99
)

// DetectionFindingActivityName is the OCSF caption of a DetectionFinding.activity_id value. It is what the
// string sibling of the identifier has to carry.
func DetectionFindingActivityName(id int) string {
	switch id {
	case 0:
		return "Unknown"
	case 1:
		return "Create"
	case 2:
		return "Update"
	case 3:
		return "Close"
	case 99:
		return "Other"
	}
	return ""
}

// DetectionFindingTypeUID values of DetectionFinding.type_uid, from the OCSF schema.
const (
	DetectionFindingTypeUIDUnknown = 200400
	// A finding was created.
	DetectionFindingTypeUIDCreate = 200401
	// A finding was updated.
	DetectionFindingTypeUIDUpdate = 200402
	// A finding was closed.
	DetectionFindingTypeUIDClose = 200403
	DetectionFindingTypeUIDOther = 200499
)

// DetectionFindingTypeUIDName is the OCSF caption of a DetectionFinding.type_uid value. It is what the
// string sibling of the identifier has to carry.
func DetectionFindingTypeUIDName(id int) string {
	switch id {
	case 200400:
		return "Detection Finding: Unknown"
	case 200401:
		return "Detection Finding: Create"
	case 200402:
		return "Detection Finding: Update"
	case 200403:
		return "Detection Finding: Close"
	case 200499:
		return "Detection Finding: Other"
	}
	return ""
}

// DeviceType values of Device.type_id, from the OCSF schema.
const (
	// The type is unknown.
	DeviceTypeUnknown = 0
	// A server.
	DeviceTypeServer = 1
	// A desktop computer.
	DeviceTypeDesktop = 2
	// A laptop computer.
	DeviceTypeLaptop = 3
	// A tablet computer.
	DeviceTypeTablet = 4
	// A mobile phone.
	DeviceTypeMobile = 5
	// A virtual machine.
	DeviceTypeVirtual = 6
	// An IOT (Internet of Things) device.
	DeviceTypeIOT = 7
	// A web browser.
	DeviceTypeBrowser = 8
	// A networking firewall.
	DeviceTypeFirewall = 9
	// A networking switch.
	DeviceTypeSwitch = 10
	// A networking hub.
	DeviceTypeHub = 11
	// A networking router.
	DeviceTypeRouter = 12
	// An intrusion detection system.
	DeviceTypeIDS = 13
	// An intrusion prevention system.
	DeviceTypeIPS = 14
	// A Load Balancer device.
	DeviceTypeLoadBalancer = 15
	// The type is not mapped. See the type attribute, which contains a data source specific value.
	DeviceTypeOther = 99
)

// DeviceTypeName is the OCSF caption of a Device.type_id value. It is what the
// string sibling of the identifier has to carry.
func DeviceTypeName(id int) string {
	switch id {
	case 0:
		return "Unknown"
	case 1:
		return "Server"
	case 2:
		return "Desktop"
	case 3:
		return "Laptop"
	case 4:
		return "Tablet"
	case 5:
		return "Mobile"
	case 6:
		return "Virtual"
	case 7:
		return "IOT"
	case 8:
		return "Browser"
	case 9:
		return "Firewall"
	case 10:
		return "Switch"
	case 11:
		return "Hub"
	case 12:
		return "Router"
	case 13:
		return "IDS"
	case 14:
		return "IPS"
	case 15:
		return "Load Balancer"
	case 99:
		return "Other"
	}
	return ""
}

// Impact values of impact_id, from the OCSF schema.
const (
	// The normalized impact is unknown.
	ImpactUnknown  = 0
	ImpactLow      = 1
	ImpactMedium   = 2
	ImpactHigh     = 3
	ImpactCritical = 4
	// The impact is not mapped. See the impact attribute, which contains a data source specific value.
	ImpactOther = 99
)

// ImpactName is the OCSF caption of a impact_id value. It is what the
// string sibling of the identifier has to carry.
func ImpactName(id int) string {
	switch id {
	case 0:
		return "Unknown"
	case 1:
		return "Low"
	case 2:
		return "Medium"
	case 3:
		return "High"
	case 4:
		return "Critical"
	case 99:
		return "Other"
	}
	return ""
}

// InventoryInfoActivity values of InventoryInfo.activity_id, from the OCSF schema.
const (
	// The event activity is unknown.
	InventoryInfoActivityUnknown = 0
	// The discovered information is via a log.
	InventoryInfoActivityLog = 1
	// The discovered information is via a collection process.
	InventoryInfoActivityCollect = 2
	// The event activity is not mapped. See the activity_name attribute, which contains a data source specific value.
	InventoryInfoActivityOther = 99
)

// InventoryInfoActivityName is the OCSF caption of a InventoryInfo.activity_id value. It is what the
// string sibling of the identifier has to carry.
func InventoryInfoActivityName(id int) string {
	switch id {
	case 0:
		return "Unknown"
	case 1:
		return "Log"
	case 2:
		return "Collect"
	case 99:
		return "Other"
	}
	return ""
}

// InventoryInfoTypeUID values of InventoryInfo.type_uid, from the OCSF schema.
const (
	InventoryInfoTypeUIDUnknown = 500100
	// The discovered information is via a log.
	InventoryInfoTypeUIDLog = 500101
	// The discovered information is via a collection process.
	InventoryInfoTypeUIDCollect = 500102
	InventoryInfoTypeUIDOther   = 500199
)

// InventoryInfoTypeUIDName is the OCSF caption of a InventoryInfo.type_uid value. It is what the
// string sibling of the identifier has to carry.
func InventoryInfoTypeUIDName(id int) string {
	switch id {
	case 500100:
		return "Device Inventory Info: Unknown"
	case 500101:
		return "Device Inventory Info: Log"
	case 500102:
		return "Device Inventory Info: Collect"
	case 500199:
		return "Device Inventory Info: Other"
	}
	return ""
}

// OSType values of OS.type_id, from the OCSF schema.
const (
	// The type is unknown.
	OSTypeUnknown = 0
	// The type is not mapped. See the type attribute, which contains a data source specific value.
	OSTypeOther         = 99
	OSTypeWindows       = 100
	OSTypeWindowsMobile = 101
	OSTypeLinux         = 200
	OSTypeAndroid       = 201
	OSTypeMacOS         = 300
	OSTypeIOS           = 301
	OSTypeIPadOS        = 302
	OSTypeSolaris       = 400
	OSTypeAIX           = 401
	OSTypeHPUX          = 402
)

// OSTypeName is the OCSF caption of a OS.type_id value. It is what the
// string sibling of the identifier has to carry.
func OSTypeName(id int) string {
	switch id {
	case 0:
		return "Unknown"
	case 99:
		return "Other"
	case 100:
		return "Windows"
	case 101:
		return "Windows Mobile"
	case 200:
		return "Linux"
	case 201:
		return "Android"
	case 300:
		return "macOS"
	case 301:
		return "iOS"
	case 302:
		return "iPadOS"
	case 400:
		return "Solaris"
	case 401:
		return "AIX"
	case 402:
		return "HP-UX"
	}
	return ""
}

// RiskLevel values of risk_level_id, from the OCSF schema.
const (
	RiskLevelInfo     = 0
	RiskLevelLow      = 1
	RiskLevelMedium   = 2
	RiskLevelHigh     = 3
	RiskLevelCritical = 4
	// The risk level is not mapped. See the risk_level attribute, which contains a data source specific value.
	RiskLevelOther = 99
)

// RiskLevelName is the OCSF caption of a risk_level_id value. It is what the
// string sibling of the identifier has to carry.
func RiskLevelName(id int) string {
	switch id {
	case 0:
		return "Info"
	case 1:
		return "Low"
	case 2:
		return "Medium"
	case 3:
		return "High"
	case 4:
		return "Critical"
	case 99:
		return "Other"
	}
	return ""
}

// Severity values of severity_id, from the OCSF schema.
const (
	// The event/finding severity is unknown.
	SeverityUnknown = 0
	// Informational message. No action required.
	SeverityInformational = 1
	// The user decides if action is needed.
	SeverityLow = 2
	// Action is required but the situation is not serious at this time.
	SeverityMedium = 3
	// Action is required immediately.
	SeverityHigh = 4
	// Action is required immediately and the scope is broad.
	SeverityCritical = 5
	// An error occurred but it is too late to take remedial action.
	SeverityFatal = 6
	// The event/finding severity is not mapped. See the severity attribute, which contains a data source specific value.
	SeverityOther = 99
)

// SeverityName is the OCSF caption of a severity_id value. It is what the
// string sibling of the identifier has to carry.
func SeverityName(id int) string {
	switch id {
	case 0:
		return "Unknown"
	case 1:
		return "Informational"
	case 2:
		return "Low"
	case 3:
		return "Medium"
	case 4:
		return "High"
	case 5:
		return "Critical"
	case 6:
		return "Fatal"
	case 99:
		return "Other"
	}
	return ""
}

// Status values of status_id, from the OCSF schema.
const (
	// The status is unknown.
	StatusUnknown = 0
	// The Finding is new and yet to be reviewed.
	StatusNew = 1
	// The Finding is under review.
	StatusInProgress = 2
	// The Finding was reviewed, determined to be benign or a false positive and is now suppressed.
	StatusSuppressed = 3
	// The Finding was reviewed, remediated and is now considered resolved.
	StatusResolved = 4
	// The event status is not mapped. See the status attribute, which contains a data source specific value.
	StatusOther = 99
)

// StatusName is the OCSF caption of a status_id value. It is what the
// string sibling of the identifier has to carry.
func StatusName(id int) string {
	switch id {
	case 0:
		return "Unknown"
	case 1:
		return "New"
	case 2:
		return "In Progress"
	case 3:
		return "Suppressed"
	case 4:
		return "Resolved"
	case 99:
		return "Other"
	}
	return ""
}

// VulnerabilityFindingActivity values of VulnerabilityFinding.activity_id, from the OCSF schema.
const (
	// The event activity is unknown.
	VulnerabilityFindingActivityUnknown = 0
	// A finding was created.
	VulnerabilityFindingActivityCreate = 1
	// A finding was updated.
	VulnerabilityFindingActivityUpdate = 2
	// A finding was closed.
	VulnerabilityFindingActivityClose = 3
	// The event activity is not mapped. See the activity_name attribute, which contains a data source specific value.
	VulnerabilityFindingActivityOther = 99
)

// VulnerabilityFindingActivityName is the OCSF caption of a VulnerabilityFinding.activity_id value. It is what the
// string sibling of the identifier has to carry.
func VulnerabilityFindingActivityName(id int) string {
	switch id {
	case 0:
		return "Unknown"
	case 1:
		return "Create"
	case 2:
		return "Update"
	case 3:
		return "Close"
	case 99:
		return "Other"
	}
	return ""
}

// VulnerabilityFindingTypeUID values of VulnerabilityFinding.type_uid, from the OCSF schema.
const (
	VulnerabilityFindingTypeUIDUnknown = 200200
	// A finding was created.
	VulnerabilityFindingTypeUIDCreate = 200201
	// A finding was updated.
	VulnerabilityFindingTypeUIDUpdate = 200202
	// A finding was closed.
	VulnerabilityFindingTypeUIDClose = 200203
	VulnerabilityFindingTypeUIDOther = 200299
)

// VulnerabilityFindingTypeUIDName is the OCSF caption of a VulnerabilityFinding.type_uid value. It is what the
// string sibling of the identifier has to carry.
func VulnerabilityFindingTypeUIDName(id int) string {
	switch id {
	case 200200:
		return "Vulnerability Finding: Unknown"
	case 200201:
		return "Vulnerability Finding: Create"
	case 200202:
		return "Vulnerability Finding: Update"
	case 200203:
		return "Vulnerability Finding: Close"
	case 200299:
		return "Vulnerability Finding: Other"
	}
	return ""
}
