apiVersion: v1
kind: Pod
metadata:
  name: pod-runasnonroot
  namespace: default
  labels:
    app: pod-runasnonroot
spec:
  containers:
  - name: app
    image: nginx:1.25
    securityContext:
      runAsNonRoot: true
