AWSTemplateFormatVersion: "2010-09-09"
Resources:
  ProdVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true

  ProdVpcEncryption:
    Type: AWS::EC2::VPCEncryptionControl
    Properties:
      VpcId: !Ref ProdVpc
      Mode: enforce
