AWSTemplateFormatVersion: "2010-09-09"
Resources:
  DataWarehouse:
    Type: AWS::Redshift::Cluster
    Properties:
      ClusterType: multi-node
      NumberOfNodes: 2
      NodeType: ra3.xlplus
      DBName: analytics
      MasterUsername: admin
      ManageMasterPassword: true
      Encrypted: true
      LoggingProperties:
        BucketName: my-redshift-audit-logs
        S3KeyPrefix: audit/
