apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-containerd-socket
  namespace: default
spec:
  schedule: '*/5 * * * *'
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: cronjob-containerd-socket
        spec:
          containers:
          - name: app
            image: nginx:1.25
            volumeMounts:
            - name: sock
              mountPath: /run/containerd/containerd.sock
          volumes:
          - name: sock
            hostPath:
              path: /run/containerd/containerd.sock
          restartPolicy: Never
