apiVersion: batch/v1
kind: Job
metadata:
  name: job-docker-socket
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: job-docker-socket
    spec:
      containers:
      - name: app
        image: nginx:1.25
        volumeMounts:
        - name: sock
          mountPath: /var/run/docker.sock
      volumes:
      - name: sock
        hostPath:
          path: /var/run/docker.sock
      restartPolicy: Never
