AWSTemplateFormatVersion: "2010-09-09"
Resources:
  AttachIgw:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: CloudTrail/DefaultLogGroup
      FilterPattern: '{ ($.eventName = AttachInternetGateway) }'
      MetricTransformations:
        - MetricName: AttachIgwMetric
          MetricNamespace: CISBenchmark
          MetricValue: "1"
