// Code generated by protoc-gen-rangerrpc version DO NOT EDIT.
// source: policy_sbom.proto

package policy

import (
	"context"
	"errors"
	"net/http"
	"net/url"
	"strings"

	ranger "go.mondoo.com/ranger-rpc"
	"go.mondoo.com/ranger-rpc/metadata"
	jsonpb "google.golang.org/protobuf/encoding/protojson"
	pb "google.golang.org/protobuf/proto"
)

// service interface definition

type Sbom interface {
	BulkUploadSbom(context.Context, *BulkUploadSbomRequest) (*BulkUploadSbomResponse, error)
}

// client implementation

type SbomClient struct {
	ranger.Client
	httpclient ranger.HTTPClient
	prefix     string
}

func NewSbomClient(addr string, client ranger.HTTPClient, plugins ...ranger.ClientPlugin) (*SbomClient, error) {
	base, err := url.Parse(ranger.SanitizeUrl(addr))
	if err != nil {
		return nil, err
	}

	u, err := url.Parse("./Sbom")
	if err != nil {
		return nil, err
	}

	serviceClient := &SbomClient{
		httpclient: client,
		prefix:     base.ResolveReference(u).String(),
	}
	serviceClient.AddPlugins(plugins...)
	return serviceClient, nil
}
func (c *SbomClient) BulkUploadSbom(ctx context.Context, in *BulkUploadSbomRequest) (*BulkUploadSbomResponse, error) {
	out := new(BulkUploadSbomResponse)
	err := c.DoClientRequest(ctx, c.httpclient, strings.Join([]string{c.prefix, "/BulkUploadSbom"}, ""), in, out)
	return out, err
}

// server implementation

type SbomServerOption func(s *SbomServer)

func WithUnknownFieldsForSbomServer() SbomServerOption {
	return func(s *SbomServer) {
		s.allowUnknownFields = true
	}
}

func NewSbomServer(handler Sbom, opts ...SbomServerOption) http.Handler {
	srv := &SbomServer{
		handler: handler,
	}

	for i := range opts {
		opts[i](srv)
	}

	service := ranger.Service{
		Name: "Sbom",
		Methods: map[string]ranger.Method{
			"BulkUploadSbom": srv.BulkUploadSbom,
		},
	}
	return ranger.NewRPCServer(&service)
}

type SbomServer struct {
	handler            Sbom
	allowUnknownFields bool
}

func (p *SbomServer) BulkUploadSbom(ctx context.Context, reqBytes *[]byte) (pb.Message, error) {
	var req BulkUploadSbomRequest
	var err error

	md, ok := metadata.FromIncomingContext(ctx)
	if !ok {
		return nil, errors.New("could not access header")
	}

	switch md.First("Content-Type") {
	case "application/protobuf", "application/octet-stream", "application/grpc+proto":
		err = pb.Unmarshal(*reqBytes, &req)
	default:
		// handle case of empty object
		if len(*reqBytes) > 0 {
			err = jsonpb.UnmarshalOptions{DiscardUnknown: true}.Unmarshal(*reqBytes, &req)
		}
	}

	if err != nil {
		return nil, err
	}
	return p.handler.BulkUploadSbom(ctx, &req)
}
