// Copyright (c) Mondoo, Inc.
// SPDX-License-Identifier: BUSL-1.1

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: policy_sbom.proto

package policy

import (
	sbom "go.mondoo.com/mql/v13/sbom"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SbomSourceName is used to identify the source of the SBOM.
type SbomSourceName int32

const (
	// SbomSourceName_SBOM_SOURCE_UNSPECIFIED represents an unspecified source
	SbomSourceName_SBOM_SOURCE_UNSPECIFIED SbomSourceName = 0
	// SbomSourceName_SBOM_SOURCE_MONDOO represents an SBOM coming from Mondoo,
	// either from cnquery or cnspec
	SbomSourceName_SBOM_SOURCE_MONDOO SbomSourceName = 1
	// SbomSourceName_SBOM_SOURCE_MSDEFENDER represents an SBOM coming from
	// Microsoft Defender
	SbomSourceName_SBOM_SOURCE_MSDEFENDER SbomSourceName = 2
	// SbomSourceName_SBOM_SOURCE_SENTINELONE represents an SBOM coming from
	// SentinelOne
	SbomSourceName_SBOM_SOURCE_SENTINELONE SbomSourceName = 3
	// SbomSourceName_SBOM_SOURCE_CROWDSTRIKE represents an SBOM coming from
	// CrowdStrike
	SbomSourceName_SBOM_SOURCE_CROWDSTRIKE SbomSourceName = 4
)

// Enum value maps for SbomSourceName.
var (
	SbomSourceName_name = map[int32]string{
		0: "SBOM_SOURCE_UNSPECIFIED",
		1: "SBOM_SOURCE_MONDOO",
		2: "SBOM_SOURCE_MSDEFENDER",
		3: "SBOM_SOURCE_SENTINELONE",
		4: "SBOM_SOURCE_CROWDSTRIKE",
	}
	SbomSourceName_value = map[string]int32{
		"SBOM_SOURCE_UNSPECIFIED": 0,
		"SBOM_SOURCE_MONDOO":      1,
		"SBOM_SOURCE_MSDEFENDER":  2,
		"SBOM_SOURCE_SENTINELONE": 3,
		"SBOM_SOURCE_CROWDSTRIKE": 4,
	}
)

func (x SbomSourceName) Enum() *SbomSourceName {
	p := new(SbomSourceName)
	*p = x
	return p
}

func (x SbomSourceName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SbomSourceName) Descriptor() protoreflect.EnumDescriptor {
	return file_policy_sbom_proto_enumTypes[0].Descriptor()
}

func (SbomSourceName) Type() protoreflect.EnumType {
	return &file_policy_sbom_proto_enumTypes[0]
}

func (x SbomSourceName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SbomSourceName.Descriptor instead.
func (SbomSourceName) EnumDescriptor() ([]byte, []int) {
	return file_policy_sbom_proto_rawDescGZIP(), []int{0}
}

// BulkUploadSbomRequest is the request for the BulkUploadSbom method.
type BulkUploadSbomRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The space_mrn is the space MRN to upload the SBOMs to.
	SpaceMrn string `protobuf:"bytes,1,opt,name=space_mrn,json=spaceMrn,proto3" json:"space_mrn,omitempty"`
	// The sboms is the list of SBOMs to upload.
	// Each SBOM includes identification information for the source and asset.
	Sboms []*sbom.Sbom `protobuf:"bytes,2,rep,name=sboms,proto3" json:"sboms,omitempty"`
	// create_assets indicates whether to create assets in the backend when they
	// are not found
	CreateAssets  bool `protobuf:"varint,3,opt,name=create_assets,json=createAssets,proto3" json:"create_assets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkUploadSbomRequest) Reset() {
	*x = BulkUploadSbomRequest{}
	mi := &file_policy_sbom_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkUploadSbomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkUploadSbomRequest) ProtoMessage() {}

func (x *BulkUploadSbomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_sbom_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkUploadSbomRequest.ProtoReflect.Descriptor instead.
func (*BulkUploadSbomRequest) Descriptor() ([]byte, []int) {
	return file_policy_sbom_proto_rawDescGZIP(), []int{0}
}

func (x *BulkUploadSbomRequest) GetSpaceMrn() string {
	if x != nil {
		return x.SpaceMrn
	}
	return ""
}

func (x *BulkUploadSbomRequest) GetSboms() []*sbom.Sbom {
	if x != nil {
		return x.Sboms
	}
	return nil
}

func (x *BulkUploadSbomRequest) GetCreateAssets() bool {
	if x != nil {
		return x.CreateAssets
	}
	return false
}

type BulkUploadSbomResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Count int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	// The asset_mrns is the list of asset MRNs that were uploaded.
	AssetMrns     []string `protobuf:"bytes,2,rep,name=asset_mrns,json=assetMrns,proto3" json:"asset_mrns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkUploadSbomResponse) Reset() {
	*x = BulkUploadSbomResponse{}
	mi := &file_policy_sbom_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkUploadSbomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkUploadSbomResponse) ProtoMessage() {}

func (x *BulkUploadSbomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_policy_sbom_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkUploadSbomResponse.ProtoReflect.Descriptor instead.
func (*BulkUploadSbomResponse) Descriptor() ([]byte, []int) {
	return file_policy_sbom_proto_rawDescGZIP(), []int{1}
}

func (x *BulkUploadSbomResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *BulkUploadSbomResponse) GetAssetMrns() []string {
	if x != nil {
		return x.AssetMrns
	}
	return nil
}

var File_policy_sbom_proto protoreflect.FileDescriptor

const file_policy_sbom_proto_rawDesc = "" +
	"\n" +
	"\x11policy_sbom.proto\x12\x10cnspec.policy.v1\x1a\x13sbom/mql_sbom.proto\"\x85\x01\n" +
	"\x15BulkUploadSbomRequest\x12\x1b\n" +
	"\tspace_mrn\x18\x01 \x01(\tR\bspaceMrn\x12*\n" +
	"\x05sboms\x18\x02 \x03(\v2\x14.mondoo.sbom.v1.SbomR\x05sboms\x12#\n" +
	"\rcreate_assets\x18\x03 \x01(\bR\fcreateAssets\"M\n" +
	"\x16BulkUploadSbomResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12\x1d\n" +
	"\n" +
	"asset_mrns\x18\x02 \x03(\tR\tassetMrns*\x9b\x01\n" +
	"\x0eSbomSourceName\x12\x1b\n" +
	"\x17SBOM_SOURCE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SBOM_SOURCE_MONDOO\x10\x01\x12\x1a\n" +
	"\x16SBOM_SOURCE_MSDEFENDER\x10\x02\x12\x1b\n" +
	"\x17SBOM_SOURCE_SENTINELONE\x10\x03\x12\x1b\n" +
	"\x17SBOM_SOURCE_CROWDSTRIKE\x10\x042m\n" +
	"\x04Sbom\x12e\n" +
	"\x0eBulkUploadSbom\x12'.cnspec.policy.v1.BulkUploadSbomRequest\x1a(.cnspec.policy.v1.BulkUploadSbomResponse\"\x00B!Z\x1fgo.mondoo.com/cnspec/v13/policyb\x06proto3"

var (
	file_policy_sbom_proto_rawDescOnce sync.Once
	file_policy_sbom_proto_rawDescData []byte
)

func file_policy_sbom_proto_rawDescGZIP() []byte {
	file_policy_sbom_proto_rawDescOnce.Do(func() {
		file_policy_sbom_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_policy_sbom_proto_rawDesc), len(file_policy_sbom_proto_rawDesc)))
	})
	return file_policy_sbom_proto_rawDescData
}

var file_policy_sbom_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_policy_sbom_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_policy_sbom_proto_goTypes = []any{
	(SbomSourceName)(0),            // 0: cnspec.policy.v1.SbomSourceName
	(*BulkUploadSbomRequest)(nil),  // 1: cnspec.policy.v1.BulkUploadSbomRequest
	(*BulkUploadSbomResponse)(nil), // 2: cnspec.policy.v1.BulkUploadSbomResponse
	(*sbom.Sbom)(nil),              // 3: mondoo.sbom.v1.Sbom
}
var file_policy_sbom_proto_depIdxs = []int32{
	3, // 0: cnspec.policy.v1.BulkUploadSbomRequest.sboms:type_name -> mondoo.sbom.v1.Sbom
	1, // 1: cnspec.policy.v1.Sbom.BulkUploadSbom:input_type -> cnspec.policy.v1.BulkUploadSbomRequest
	2, // 2: cnspec.policy.v1.Sbom.BulkUploadSbom:output_type -> cnspec.policy.v1.BulkUploadSbomResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_policy_sbom_proto_init() }
func file_policy_sbom_proto_init() {
	if File_policy_sbom_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_policy_sbom_proto_rawDesc), len(file_policy_sbom_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_policy_sbom_proto_goTypes,
		DependencyIndexes: file_policy_sbom_proto_depIdxs,
		EnumInfos:         file_policy_sbom_proto_enumTypes,
		MessageInfos:      file_policy_sbom_proto_msgTypes,
	}.Build()
	File_policy_sbom_proto = out.File
	file_policy_sbom_proto_goTypes = nil
	file_policy_sbom_proto_depIdxs = nil
}
