AWSTemplateFormatVersion: "2010-09-09"
Resources:
  TrailLogging:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: CloudTrail/DefaultLogGroup
      FilterPattern: '{ ($.eventName = StopLogging) }'
      MetricTransformations:
        - MetricName: TrailLoggingMetric
          MetricNamespace: CISBenchmark
          MetricValue: "1"
