apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-hostpath-readonly
  namespace: default
spec:
  selector:
    matchLabels:
      app: replicaset-hostpath-readonly
  template:
    metadata:
      labels:
        app: replicaset-hostpath-readonly
    spec:
      containers:
      - name: app
        image: nginx:1.25
        volumeMounts:
        - name: hp
          mountPath: /data
          readOnly: true
      volumes:
      - name: hp
        hostPath:
          path: /data
  replicas: 1
