apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-docker-socket
  namespace: default
spec:
  schedule: '*/5 * * * *'
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: cronjob-docker-socket
        spec:
          containers:
          - name: app
            image: nginx:1.25
          restartPolicy: Never
