AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyGraphQLApi:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: my-api
      AuthenticationType: AMAZON_COGNITO_USER_POOLS
      UserPoolConfig:
        UserPoolId: us-east-1_abc123
        AwsRegion: us-east-1
        DefaultAction: ALLOW
