apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-readonlyrootfilesystem
  namespace: default
spec:
  selector:
    matchLabels:
      app: statefulset-readonlyrootfilesystem
  template:
    metadata:
      labels:
        app: statefulset-readonlyrootfilesystem
    spec:
      containers:
      - name: app
        image: nginx:1.25
        securityContext:
          readOnlyRootFilesystem: false
  replicas: 1
  serviceName: statefulset-readonlyrootfilesystem
