apiVersion: batch/v1
kind: Job
metadata:
  name: job-serviceaccount
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: job-serviceaccount
    spec:
      containers:
      - name: app
        image: nginx:1.25
      serviceAccountName: myapp-sa
      restartPolicy: Never
