AWSTemplateFormatVersion: "2010-09-09"
Resources:
  AppTask:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: app
      ContainerDefinitions:
        - Name: app
          Image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/app:latest
          Essential: true
          ReadonlyRootFilesystem: true
        - Name: sidecar
          Image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/sidecar:latest
          Essential: false
          ReadonlyRootFilesystem: true
