apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-serviceaccount
  namespace: default
spec:
  selector:
    matchLabels:
      app: replicaset-serviceaccount
  template:
    metadata:
      labels:
        app: replicaset-serviceaccount
    spec:
      containers:
      - name: app
        image: nginx:1.25
      serviceAccountName: default
      automountServiceAccountToken: true
  replicas: 1
