AWSTemplateFormatVersion: "2010-09-09"
Resources:
  AppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Kubelet exposed to the internet
      VpcId: vpc-0abcd1234ef567890
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 10250
          ToPort: 10255
          CidrIp: 0.0.0.0/0
