AWSTemplateFormatVersion: "2010-09-09"
Resources:
  DeleteNacl:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: CloudTrail/DefaultLogGroup
      FilterPattern: '{ ($.eventName = DeleteNetworkAcl) }'
      MetricTransformations:
        - MetricName: DeleteNaclMetric
          MetricNamespace: CISBenchmark
          MetricValue: "1"
