AWSTemplateFormatVersion: "2010-09-09"
Resources:
  WebAcl:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: my-web-acl
      Scope: REGIONAL
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: myWebAcl
