apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-ports-hostport
  namespace: default
spec:
  selector:
    matchLabels:
      app: statefulset-ports-hostport
  template:
    metadata:
      labels:
        app: statefulset-ports-hostport
    spec:
      containers:
      - name: app
        image: nginx:1.25
        ports:
        - containerPort: 8080
          hostPort: 8080
  replicas: 1
  serviceName: statefulset-ports-hostport
