AWSTemplateFormatVersion: "2010-09-09"
Resources:
  ExampleDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: fail-absent
      Engine: postgres
      DBInstanceClass: db.t3.medium
      AllocatedStorage: "20"
