AWSTemplateFormatVersion: "2010-09-09"
Resources:
  RootCA:
    Type: AWS::ACMPCA::CertificateAuthority
    Properties:
      Type: ROOT
      KeyAlgorithm: RSA_2048
      SigningAlgorithm: SHA256WITHRSA
      KeyStorageSecurityStandard: FIPS_140_2_LEVEL_3_OR_HIGHER
      Subject:
        Organization: Example Corp
        CommonName: Example Root CA
