AWSTemplateFormatVersion: "2010-09-09"
Resources:
  OptionsRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: "OPTIONS /items"
      AuthorizationType: NONE
      Target: !Sub "integrations/${MyIntegration}"
