AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: my-s3-origin
          ViewerProtocolPolicy: redirect-to-https
        Origins:
          - Id: my-s3-origin
            DomainName: my-bucket.s3.us-east-1.amazonaws.com
            S3OriginConfig:
              OriginAccessIdentity: ""
