apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-limitcpu
  namespace: default
spec:
  selector:
    matchLabels:
      app: replicaset-limitcpu
  template:
    metadata:
      labels:
        app: replicaset-limitcpu
    spec:
      containers:
      - name: app
        image: nginx:1.25
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
  replicas: 1
