AWSTemplateFormatVersion: "2010-09-09"
Resources:
  S3PolicyChangesMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: /aws/cloudtrail/logs
      FilterPattern: '{ ($.eventSource = s3.amazonaws.com) && (($.eventName = PutBucketAcl) || ($.eventName = PutBucketPolicy) || ($.eventName = PutBucketCors) || ($.eventName = DeleteBucketPolicy) || ($.eventName = DeleteBucketCors)) }'
      MetricTransformations:
        - MetricName: S3BucketPolicyChanges
          MetricNamespace: CISBenchmark
          MetricValue: "1"
