AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyModel:
    Type: AWS::SageMaker::Model
    Properties:
      ModelName: my-model
      ExecutionRoleArn: arn:aws:iam::123456789012:role/SageMakerRole
      EnableNetworkIsolation: false
      PrimaryContainer:
        Image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/my-model:latest
