AWSTemplateFormatVersion: "2010-09-09"
Resources:
  SearchDomain:
    Type: AWS::OpenSearchService::Domain
    Properties:
      DomainName: prod-search
      EngineVersion: OpenSearch_2.11
      VPCOptions:
        SubnetIds:
          - subnet-0abc1234
        SecurityGroupIds:
          - sg-0123456789abcdef0
