apiVersion: v1
kind: Pod
metadata:
  name: pod-crio-socket
  namespace: default
  labels:
    app: pod-crio-socket
spec:
  containers:
  - name: app
    image: nginx:1.25
    volumeMounts:
    - name: sock
      mountPath: /var/run/crio/crio.sock
  volumes:
  - name: sock
    hostPath:
      path: /var/run/crio/crio.sock
