AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        WebACLId: arn:aws:wafv2:us-east-1:123456789012:global/webacl/my-acl/abcd-1234
        DefaultCacheBehavior:
          TargetOriginId: my-origin
          ViewerProtocolPolicy: redirect-to-https
        Origins:
          - Id: my-origin
            DomainName: example.com
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
