AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: my-bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: DenyWhenSecure
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource: "arn:aws:s3:::my-bucket/*"
            Condition:
              Bool:
                "aws:SecureTransport": "true"
