AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyDomain:
    Type: AWS::OpenSearchService::Domain
    Properties:
      DomainName: my-domain
      SoftwareUpdateOptions:
        AutoSoftwareUpdateEnabled: true
