AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: my-origin
          ViewerProtocolPolicy: https-only
        Origins:
          - Id: my-origin
            DomainName: example.com
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
