AWSTemplateFormatVersion: "2010-09-09"
Resources:
  FileSystem:
    Type: AWS::FSx::FileSystem
    Properties:
      FileSystemType: LUSTRE
      StorageCapacity: 1200
      SubnetIds:
        - subnet-0abc1234def567890
      LustreConfiguration:
        DeploymentType: PERSISTENT_2
