AWSTemplateFormatVersion: "2010-09-09"
Resources:
  EventBusPolicy:
    Type: AWS::Events::EventBusPolicy
    Properties:
      EventBusName: my-event-bus
      StatementId: AllowOrgWithCondition
      Statement:
        Sid: AllowOrgWithCondition
        Effect: Allow
        Principal: "*"
        Action: events:PutEvents
        Resource: arn:aws:events:us-east-1:210987654321:event-bus/my-event-bus
        Condition:
          StringEquals:
            aws:PrincipalOrgID: o-abc123def4
