apiVersion: v1
kind: Pod
metadata:
  name: pod-limitmemory
  namespace: default
  labels:
    app: pod-limitmemory
spec:
  containers:
  - name: app
    image: nginx:1.25
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
