apiVersion: batch/v1
kind: Job
metadata:
  name: job-imagepull
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: job-imagepull
    spec:
      containers:
      - name: app
        image: nginx:1.25
        imagePullPolicy: Always
      restartPolicy: Never
