AWSTemplateFormatVersion: "2010-09-09"
Resources:
  NaclChanges:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: CloudTrail/DefaultLogGroup
      FilterPattern: '{ ($.eventName = CreateNetworkAcl) || ($.eventName = CreateNetworkAclEntry) || ($.eventName = DeleteNetworkAcl) || ($.eventName = DeleteNetworkAclEntry) || ($.eventName = ReplaceNetworkAclEntry) }'
      MetricTransformations:
        - MetricName: NaclChangesMetric
          MetricNamespace: CISBenchmark
          MetricValue: "1"
