AWSTemplateFormatVersion: "2010-09-09"
Resources:
  FtpServer:
    Type: AWS::Transfer::Server
    Properties:
      Protocols:
        - FTP
      EndpointType: VPC
      IdentityProviderType: API_GATEWAY
      IdentityProviderDetails:
        Url: https://api.example.com/auth
        InvocationRole: arn:aws:iam::123456789012:role/transfer-invocation
