apiVersion: v1
kind: Pod
metadata:
  name: pod-capability-drop-all
  namespace: default
  labels:
    app: pod-capability-drop-all
spec:
  containers:
  - name: app
    image: nginx:1.25
    securityContext:
      capabilities:
        drop:
        - ALL
