AWSTemplateFormatVersion: "2010-09-09"
Resources:
  ConsoleSuccess:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: CloudTrail/DefaultLogGroup
      FilterPattern: '{ ($.eventName = ConsoleLogin) && ($.responseElements.ConsoleLogin = "Success") }'
      MetricTransformations:
        - MetricName: ConsoleSuccessMetric
          MetricNamespace: CISBenchmark
          MetricValue: "1"
