AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: my-origin
          ViewerProtocolPolicy: redirect-to-https
        Origins:
          - Id: my-origin
            DomainName: example.com
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:123456789012:certificate/abcd-1234
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
