apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset-ports-hostport
  namespace: default
spec:
  selector:
    matchLabels:
      app: daemonset-ports-hostport
  template:
    metadata:
      labels:
        app: daemonset-ports-hostport
    spec:
      containers:
      - name: app
        image: nginx:1.25
        ports:
        - containerPort: 8080
          hostPort: 8080
