apiVersion: batch/v1
kind: Job
metadata:
  name: job-hostnetwork
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: job-hostnetwork
    spec:
      containers:
      - name: app
        image: nginx:1.25
      restartPolicy: Never
