// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.getDataStmt, err = db.PrepareContext(ctx, getData); err != nil {
		return nil, fmt.Errorf("error preparing query GetData: %w", err)
	}
	if q.getMetadataStmt, err = db.PrepareContext(ctx, getMetadata); err != nil {
		return nil, fmt.Errorf("error preparing query GetMetadata: %w", err)
	}
	if q.getMetadataByKeyStmt, err = db.PrepareContext(ctx, getMetadataByKey); err != nil {
		return nil, fmt.Errorf("error preparing query GetMetadataByKey: %w", err)
	}
	if q.getResourceStmt, err = db.PrepareContext(ctx, getResource); err != nil {
		return nil, fmt.Errorf("error preparing query GetResource: %w", err)
	}
	if q.getRiskFactorStmt, err = db.PrepareContext(ctx, getRiskFactor); err != nil {
		return nil, fmt.Errorf("error preparing query GetRiskFactor: %w", err)
	}
	if q.getScoreStmt, err = db.PrepareContext(ctx, getScore); err != nil {
		return nil, fmt.Errorf("error preparing query GetScore: %w", err)
	}
	if q.insertDataStmt, err = db.PrepareContext(ctx, insertData); err != nil {
		return nil, fmt.Errorf("error preparing query InsertData: %w", err)
	}
	if q.insertMetadataStmt, err = db.PrepareContext(ctx, insertMetadata); err != nil {
		return nil, fmt.Errorf("error preparing query InsertMetadata: %w", err)
	}
	if q.insertResourceStmt, err = db.PrepareContext(ctx, insertResource); err != nil {
		return nil, fmt.Errorf("error preparing query InsertResource: %w", err)
	}
	if q.insertRiskFactorStmt, err = db.PrepareContext(ctx, insertRiskFactor); err != nil {
		return nil, fmt.Errorf("error preparing query InsertRiskFactor: %w", err)
	}
	if q.insertScoreStmt, err = db.PrepareContext(ctx, insertScore); err != nil {
		return nil, fmt.Errorf("error preparing query InsertScore: %w", err)
	}
	if q.streamDataStmt, err = db.PrepareContext(ctx, streamData); err != nil {
		return nil, fmt.Errorf("error preparing query StreamData: %w", err)
	}
	if q.streamResourcesStmt, err = db.PrepareContext(ctx, streamResources); err != nil {
		return nil, fmt.Errorf("error preparing query StreamResources: %w", err)
	}
	if q.streamRiskFactorsStmt, err = db.PrepareContext(ctx, streamRiskFactors); err != nil {
		return nil, fmt.Errorf("error preparing query StreamRiskFactors: %w", err)
	}
	if q.streamScoresStmt, err = db.PrepareContext(ctx, streamScores); err != nil {
		return nil, fmt.Errorf("error preparing query StreamScores: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.getDataStmt != nil {
		if cerr := q.getDataStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDataStmt: %w", cerr)
		}
	}
	if q.getMetadataStmt != nil {
		if cerr := q.getMetadataStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMetadataStmt: %w", cerr)
		}
	}
	if q.getMetadataByKeyStmt != nil {
		if cerr := q.getMetadataByKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMetadataByKeyStmt: %w", cerr)
		}
	}
	if q.getResourceStmt != nil {
		if cerr := q.getResourceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getResourceStmt: %w", cerr)
		}
	}
	if q.getRiskFactorStmt != nil {
		if cerr := q.getRiskFactorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRiskFactorStmt: %w", cerr)
		}
	}
	if q.getScoreStmt != nil {
		if cerr := q.getScoreStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getScoreStmt: %w", cerr)
		}
	}
	if q.insertDataStmt != nil {
		if cerr := q.insertDataStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertDataStmt: %w", cerr)
		}
	}
	if q.insertMetadataStmt != nil {
		if cerr := q.insertMetadataStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertMetadataStmt: %w", cerr)
		}
	}
	if q.insertResourceStmt != nil {
		if cerr := q.insertResourceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertResourceStmt: %w", cerr)
		}
	}
	if q.insertRiskFactorStmt != nil {
		if cerr := q.insertRiskFactorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertRiskFactorStmt: %w", cerr)
		}
	}
	if q.insertScoreStmt != nil {
		if cerr := q.insertScoreStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertScoreStmt: %w", cerr)
		}
	}
	if q.streamDataStmt != nil {
		if cerr := q.streamDataStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing streamDataStmt: %w", cerr)
		}
	}
	if q.streamResourcesStmt != nil {
		if cerr := q.streamResourcesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing streamResourcesStmt: %w", cerr)
		}
	}
	if q.streamRiskFactorsStmt != nil {
		if cerr := q.streamRiskFactorsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing streamRiskFactorsStmt: %w", cerr)
		}
	}
	if q.streamScoresStmt != nil {
		if cerr := q.streamScoresStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing streamScoresStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                    DBTX
	tx                    *sql.Tx
	getDataStmt           *sql.Stmt
	getMetadataStmt       *sql.Stmt
	getMetadataByKeyStmt  *sql.Stmt
	getResourceStmt       *sql.Stmt
	getRiskFactorStmt     *sql.Stmt
	getScoreStmt          *sql.Stmt
	insertDataStmt        *sql.Stmt
	insertMetadataStmt    *sql.Stmt
	insertResourceStmt    *sql.Stmt
	insertRiskFactorStmt  *sql.Stmt
	insertScoreStmt       *sql.Stmt
	streamDataStmt        *sql.Stmt
	streamResourcesStmt   *sql.Stmt
	streamRiskFactorsStmt *sql.Stmt
	streamScoresStmt      *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                    tx,
		tx:                    tx,
		getDataStmt:           q.getDataStmt,
		getMetadataStmt:       q.getMetadataStmt,
		getMetadataByKeyStmt:  q.getMetadataByKeyStmt,
		getResourceStmt:       q.getResourceStmt,
		getRiskFactorStmt:     q.getRiskFactorStmt,
		getScoreStmt:          q.getScoreStmt,
		insertDataStmt:        q.insertDataStmt,
		insertMetadataStmt:    q.insertMetadataStmt,
		insertResourceStmt:    q.insertResourceStmt,
		insertRiskFactorStmt:  q.insertRiskFactorStmt,
		insertScoreStmt:       q.insertScoreStmt,
		streamDataStmt:        q.streamDataStmt,
		streamResourcesStmt:   q.streamResourcesStmt,
		streamRiskFactorsStmt: q.streamRiskFactorsStmt,
		streamScoresStmt:      q.streamScoresStmt,
	}
}
