// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type Datum struct {
	CodeID string `json:"code_id"`
	Data   []byte `json:"data"`
}

type Metadata struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Resource struct {
	Name string `json:"name"`
	ID   string `json:"id"`
	Data []byte `json:"data"`
}

type Score struct {
	QrID        string         `json:"qr_id"`
	RiskScore   int64          `json:"risk_score"`
	Type        int64          `json:"type"`
	Value       int64          `json:"value"`
	Weight      int64          `json:"weight"`
	Message     sql.NullString `json:"message"`
	RiskFactors []byte         `json:"risk_factors"`
	Sources     []byte         `json:"sources"`
}

type ScoredRiskFactor struct {
	Mrn        string  `json:"mrn"`
	Risk       float64 `json:"risk"`
	IsToxic    bool    `json:"is_toxic"`
	IsDetected bool    `json:"is_detected"`
}
