// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	GetAsset(ctx context.Context) ([]byte, error)
	GetData(ctx context.Context, codeID string) ([]byte, error)
	GetMetadata(ctx context.Context) ([]Metadata, error)
	GetMetadataByKey(ctx context.Context, key string) (string, error)
	GetResource(ctx context.Context, arg GetResourceParams) ([]byte, error)
	GetRiskFactor(ctx context.Context, mrn string) (ScoredRiskFactor, error)
	GetScore(ctx context.Context, qrID string) (Score, error)
	// Asset operations (added in schema 1.1)
	InsertAsset(ctx context.Context, data []byte) error
	// Data operations
	InsertData(ctx context.Context, arg InsertDataParams) error
	// Copyright Mondoo, Inc. 2024, 2026
	// SPDX-License-Identifier: BUSL-1.1
	// Metadata operations
	InsertMetadata(ctx context.Context, arg InsertMetadataParams) error
	// Resource operations
	InsertResource(ctx context.Context, arg InsertResourceParams) error
	// Risk factor operations
	InsertRiskFactor(ctx context.Context, arg InsertRiskFactorParams) error
	// Scores operations
	InsertScore(ctx context.Context, arg InsertScoreParams) error
	StreamData(ctx context.Context) ([]Datum, error)
	StreamResources(ctx context.Context) ([]Resource, error)
	StreamRiskFactors(ctx context.Context) ([]ScoredRiskFactor, error)
	StreamScores(ctx context.Context) ([]Score, error)
}

var _ Querier = (*Queries)(nil)
