// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getData = `-- name: GetData :one
SELECT data FROM data WHERE code_id = ?
`

func (q *Queries) GetData(ctx context.Context, codeID string) ([]byte, error) {
	row := q.queryRow(ctx, q.getDataStmt, getData, codeID)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const getMetadata = `-- name: GetMetadata :many
SELECT key, value FROM metadata
`

func (q *Queries) GetMetadata(ctx context.Context) ([]Metadata, error) {
	rows, err := q.query(ctx, q.getMetadataStmt, getMetadata)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Metadata
	for rows.Next() {
		var i Metadata
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMetadataByKey = `-- name: GetMetadataByKey :one
SELECT value FROM metadata WHERE key = ?
`

func (q *Queries) GetMetadataByKey(ctx context.Context, key string) (string, error) {
	row := q.queryRow(ctx, q.getMetadataByKeyStmt, getMetadataByKey, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getResource = `-- name: GetResource :one
SELECT data FROM resources WHERE name = ? AND id = ?
`

type GetResourceParams struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

func (q *Queries) GetResource(ctx context.Context, arg GetResourceParams) ([]byte, error) {
	row := q.queryRow(ctx, q.getResourceStmt, getResource, arg.Name, arg.ID)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const getRiskFactor = `-- name: GetRiskFactor :one
SELECT mrn, risk, is_toxic, is_detected
FROM scored_risk_factors WHERE mrn = ?
`

func (q *Queries) GetRiskFactor(ctx context.Context, mrn string) (ScoredRiskFactor, error) {
	row := q.queryRow(ctx, q.getRiskFactorStmt, getRiskFactor, mrn)
	var i ScoredRiskFactor
	err := row.Scan(
		&i.Mrn,
		&i.Risk,
		&i.IsToxic,
		&i.IsDetected,
	)
	return i, err
}

const getScore = `-- name: GetScore :one
SELECT qr_id, risk_score, type, value, weight, message, risk_factors, sources
FROM scores WHERE qr_id = ?
`

func (q *Queries) GetScore(ctx context.Context, qrID string) (Score, error) {
	row := q.queryRow(ctx, q.getScoreStmt, getScore, qrID)
	var i Score
	err := row.Scan(
		&i.QrID,
		&i.RiskScore,
		&i.Type,
		&i.Value,
		&i.Weight,
		&i.Message,
		&i.RiskFactors,
		&i.Sources,
	)
	return i, err
}

const insertData = `-- name: InsertData :exec
INSERT OR REPLACE INTO data (code_id, data) VALUES (?, ?)
`

type InsertDataParams struct {
	CodeID string `json:"code_id"`
	Data   []byte `json:"data"`
}

// Data operations
func (q *Queries) InsertData(ctx context.Context, arg InsertDataParams) error {
	_, err := q.exec(ctx, q.insertDataStmt, insertData, arg.CodeID, arg.Data)
	return err
}

const insertMetadata = `-- name: InsertMetadata :exec

INSERT INTO metadata (key, value) VALUES (?, ?)
`

type InsertMetadataParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// Copyright (c) Mondoo, Inc.
// SPDX-License-Identifier: BUSL-1.1
// Metadata operations
func (q *Queries) InsertMetadata(ctx context.Context, arg InsertMetadataParams) error {
	_, err := q.exec(ctx, q.insertMetadataStmt, insertMetadata, arg.Key, arg.Value)
	return err
}

const insertResource = `-- name: InsertResource :exec
INSERT OR REPLACE INTO resources (name, id, data) VALUES (?, ?, ?)
`

type InsertResourceParams struct {
	Name string `json:"name"`
	ID   string `json:"id"`
	Data []byte `json:"data"`
}

// Resource operations
func (q *Queries) InsertResource(ctx context.Context, arg InsertResourceParams) error {
	_, err := q.exec(ctx, q.insertResourceStmt, insertResource, arg.Name, arg.ID, arg.Data)
	return err
}

const insertRiskFactor = `-- name: InsertRiskFactor :exec
INSERT OR REPLACE INTO scored_risk_factors (mrn, risk, is_toxic, is_detected)
VALUES (?, ?, ?, ?)
`

type InsertRiskFactorParams struct {
	Mrn        string  `json:"mrn"`
	Risk       float64 `json:"risk"`
	IsToxic    bool    `json:"is_toxic"`
	IsDetected bool    `json:"is_detected"`
}

// Risk factor operations
func (q *Queries) InsertRiskFactor(ctx context.Context, arg InsertRiskFactorParams) error {
	_, err := q.exec(ctx, q.insertRiskFactorStmt, insertRiskFactor,
		arg.Mrn,
		arg.Risk,
		arg.IsToxic,
		arg.IsDetected,
	)
	return err
}

const insertScore = `-- name: InsertScore :exec
INSERT OR REPLACE INTO scores (
    qr_id, risk_score, type, value, weight, message, risk_factors, sources
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertScoreParams struct {
	QrID        string         `json:"qr_id"`
	RiskScore   int64          `json:"risk_score"`
	Type        int64          `json:"type"`
	Value       int64          `json:"value"`
	Weight      int64          `json:"weight"`
	Message     sql.NullString `json:"message"`
	RiskFactors []byte         `json:"risk_factors"`
	Sources     []byte         `json:"sources"`
}

// Scores operations
func (q *Queries) InsertScore(ctx context.Context, arg InsertScoreParams) error {
	_, err := q.exec(ctx, q.insertScoreStmt, insertScore,
		arg.QrID,
		arg.RiskScore,
		arg.Type,
		arg.Value,
		arg.Weight,
		arg.Message,
		arg.RiskFactors,
		arg.Sources,
	)
	return err
}

const streamData = `-- name: StreamData :many
SELECT code_id, data FROM data ORDER BY code_id
`

func (q *Queries) StreamData(ctx context.Context) ([]Datum, error) {
	rows, err := q.query(ctx, q.streamDataStmt, streamData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Datum
	for rows.Next() {
		var i Datum
		if err := rows.Scan(&i.CodeID, &i.Data); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const streamResources = `-- name: StreamResources :many
SELECT name, id, data FROM resources ORDER BY name, id
`

func (q *Queries) StreamResources(ctx context.Context) ([]Resource, error) {
	rows, err := q.query(ctx, q.streamResourcesStmt, streamResources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resource
	for rows.Next() {
		var i Resource
		if err := rows.Scan(&i.Name, &i.ID, &i.Data); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const streamRiskFactors = `-- name: StreamRiskFactors :many
SELECT mrn, risk, is_toxic, is_detected
FROM scored_risk_factors ORDER BY mrn
`

func (q *Queries) StreamRiskFactors(ctx context.Context) ([]ScoredRiskFactor, error) {
	rows, err := q.query(ctx, q.streamRiskFactorsStmt, streamRiskFactors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScoredRiskFactor
	for rows.Next() {
		var i ScoredRiskFactor
		if err := rows.Scan(
			&i.Mrn,
			&i.Risk,
			&i.IsToxic,
			&i.IsDetected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const streamScores = `-- name: StreamScores :many
SELECT qr_id, risk_score, type, value, weight, message, risk_factors, sources
FROM scores ORDER BY qr_id
`

func (q *Queries) StreamScores(ctx context.Context) ([]Score, error) {
	rows, err := q.query(ctx, q.streamScoresStmt, streamScores)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Score
	for rows.Next() {
		var i Score
		if err := rows.Scan(
			&i.QrID,
			&i.RiskScore,
			&i.Type,
			&i.Value,
			&i.Weight,
			&i.Message,
			&i.RiskFactors,
			&i.Sources,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
