AWSTemplateFormatVersion: "2010-09-09"
Resources:
  Cluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: prod
      RoleArn: arn:aws:iam::123456789012:role/eks-cluster-role
      AccessConfig:
        AuthenticationMode: API_AND_CONFIG_MAP
      ResourcesVpcConfig:
        SubnetIds:
          - subnet-0abc1234
          - subnet-0def5678
