apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset-containerd-socket
  namespace: default
spec:
  selector:
    matchLabels:
      app: daemonset-containerd-socket
  template:
    metadata:
      labels:
        app: daemonset-containerd-socket
    spec:
      containers:
      - name: app
        image: nginx:1.25
