AWSTemplateFormatVersion: "2010-09-09"
Resources:
  QueryLogConfig:
    Type: AWS::Route53Resolver::ResolverQueryLoggingConfig
    Properties:
      Name: vpc-dns-query-log
      DestinationArn: arn:aws:logs:us-east-1:123456789012:log-group:/aws/route53/dns-queries
