AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyDomain:
    Type: AWS::SageMaker::Domain
    Properties:
      DomainName: my-domain
      AuthMode: IAM
      VpcId: vpc-0123456789abcdef0
      SubnetIds:
        - subnet-0123456789abcdef0
      DefaultUserSettings:
        ExecutionRole: arn:aws:iam::123456789012:role/SageMakerRole
