// Copyright Mondoo, Inc. 2024, 2026
// SPDX-License-Identifier: BUSL-1.1

syntax = "proto3";

package mondoo.report.cnspec.v1;

option go_package = "go.mondoo.com/cnspec/cli/reporter";

import "cli/reporter/mql_report.proto";

message Report {
  map <string, mondoo.report.mql.v1.Asset> assets = 1;
  map <string, mondoo.report.mql.v1.DataValues> data = 2;
  map <string, string> errors = 3;
  map <string, ScoreValues> scores = 4;
}

message ScoreValues {
  map <string, ScoreValue> values = 1;
}

message ScoreValue {
  // 1 was score, replaced by riskScore below
  reserved 1;
  reserved "score";

  string status = 2;
  uint32 riskScore = 3;
}