AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: my-project
      ServiceRole: arn:aws:iam::123456789012:role/codebuild-role
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:4.0
      Source:
        Type: NO_SOURCE
