AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyFleet:
    Type: AWS::AppStream::Fleet
    Properties:
      Name: my-fleet
      InstanceType: stream.standard.medium
      FleetType: ON_DEMAND
      ComputeCapacity:
        DesiredInstances: 2
      VpcConfig:
        SubnetIds:
          - subnet-12345678
