apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-limitmemory
  namespace: default
spec:
  selector:
    matchLabels:
      app: statefulset-limitmemory
  template:
    metadata:
      labels:
        app: statefulset-limitmemory
    spec:
      containers:
      - name: app
        image: nginx:1.25
        resources:
          limits:
            cpu: 500m
  replicas: 1
  serviceName: statefulset-limitmemory
