AWSTemplateFormatVersion: "2010-09-09"
Resources:
  Hub:
    Type: AWS::SecurityHub::Hub
    Properties:
      EnableDefaultStandards: false
  CisStandard:
    Type: AWS::SecurityHub::Standard
    Properties:
      StandardsArn: arn:aws:securityhub:us-east-1::standards/aws-foundational-security-best-practices/v/1.0.0
