AWSTemplateFormatVersion: "2010-09-09"
Resources:
  PerimeterFirewall:
    Type: AWS::NetworkFirewall::Firewall
    Properties:
      FirewallName: perimeter
      FirewallPolicyArn: arn:aws:network-firewall:us-east-1:123456789012:firewall-policy/perimeter
      VpcId: vpc-0123456789abcdef0
      DeleteProtection: true
      FirewallPolicyChangeProtection: true
      SubnetChangeProtection: true
      SubnetMappings:
        - SubnetId: subnet-0123456789abcdef0
