AWSTemplateFormatVersion: "2010-09-09"
Resources:
  IamPolicyChanges:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: CloudTrail/DefaultLogGroup
      FilterPattern: '{($.eventName=DeleteGroupPolicy)||($.eventName=PutRolePolicy)||($.eventName=CreatePolicy)||($.eventName=DeletePolicy)||($.eventName=AttachRolePolicy)||($.eventName=DetachRolePolicy)}'
      MetricTransformations:
        - MetricName: IamPolicyChangesMetric
          MetricNamespace: CISBenchmark
          MetricValue: "1"
