// Copyright Mondoo, Inc. 2024, 2026
// SPDX-License-Identifier: BUSL-1.1

// Code generated by reports/ocsf/internal/gen from the compiled OCSF
// schemas in schemas/ and the attribute list in gen.yaml. DO NOT EDIT.

package ocsf

// Event classes cnspec emits.
const (
	// ComplianceFinding identity, from the OCSF schema.
	ClassUIDComplianceFinding     = 2003
	ClassNameComplianceFinding    = "Compliance Finding"
	ClassComplianceFinding        = "compliance_finding"
	CategoryUIDComplianceFinding  = 2
	CategoryNameComplianceFinding = "Findings"

	// DetectionFinding identity, from the OCSF schema.
	ClassUIDDetectionFinding     = 2004
	ClassNameDetectionFinding    = "Detection Finding"
	ClassDetectionFinding        = "detection_finding"
	CategoryUIDDetectionFinding  = 2
	CategoryNameDetectionFinding = "Findings"

	// InventoryInfo identity, from the OCSF schema.
	ClassUIDInventoryInfo     = 5001
	ClassNameInventoryInfo    = "Device Inventory Info"
	ClassInventoryInfo        = "inventory_info"
	CategoryUIDInventoryInfo  = 5
	CategoryNameInventoryInfo = "Discovery"

	// VulnerabilityFinding identity, from the OCSF schema.
	ClassUIDVulnerabilityFinding     = 2002
	ClassNameVulnerabilityFinding    = "Vulnerability Finding"
	ClassVulnerabilityFinding        = "vulnerability_finding"
	CategoryUIDVulnerabilityFinding  = 2
	CategoryNameVulnerabilityFinding = "Findings"
)

// OCSF profiles. An attribute that belongs to a profile is only valid on an
// event whose metadata declares the profile.
const (
	ProfileCloud              = "cloud"
	ProfileContainer          = "container"
	ProfileDataClassification = "data_classification"
	ProfileDatetime           = "datetime"
	ProfileHost               = "host"
	ProfileOsint              = "osint"
	ProfileSecurityControl    = "security_control"
)

// AnalyticType values of Analytic.type_id, from the OCSF schema.
const (
	// The type is unknown.
	AnalyticTypeUnknown = 0
	// A Rule in security analytics refers to predefined criteria or conditions set to monitor, alert, or enforce policies, playing a crucial role in access control, threat detection, and regulatory compliance across security systems.
	AnalyticTypeRule = 1
	// Behavioral analytics focus on monitoring and analyzing user or system actions to identify deviations from established patterns, aiding in the detection of insider threats, fraud, and advanced persistent threats (APTs).
	AnalyticTypeBehavioral = 2
	// Statistical analytics pertains to analyzing data patterns and anomalies using statistical models to predict, detect, and respond to potential threats, enhancing overall security posture through informed decision-making.
	AnalyticTypeStatistical = 3
	// Learning (ML/DL) encompasses techniques that can "learn" from known data to create analytics that generalize to new data. There may be a statistical component to these techniques, but it is not a requirement.
	AnalyticTypeLearningMLDL = 4
	// Fingerprinting is the technique of collecting detailed system data, including software versions and configurations, to enhance threat detection, data loss prevention (DLP), and endpoint detection and response (EDR) capabilities.
	AnalyticTypeFingerprinting = 5
	// Tagging refers to the practice of assigning labels or identifiers to data, users, assets, or activities to monitor, control access, and facilitate incident response across various security domains such as DLP and EDR.
	AnalyticTypeTagging = 6
	// Keyword Match involves scanning content for specific terms to identify sensitive information, potential threats, or policy violations, aiding in DLP and compliance monitoring.
	AnalyticTypeKeywordMatch = 7
	// Regular Expressions are used to define complex search patterns for identifying, validating, and extracting specific data sets or threats within digital content, enhancing DLP, EDR, and threat detection mechanisms.
	AnalyticTypeRegularExpressions = 8
	// Exact Data Match is a precise comparison technique used to detect the unauthorized use or exposure of specific, sensitive information, crucial for enforcing DLP policies and protecting against data breaches.
	AnalyticTypeExactDataMatch = 9
	// Partial Data Match involves identifying instances where segments of sensitive information or patterns match, facilitating nuanced DLP and threat detection without requiring complete data conformity.
	AnalyticTypePartialDataMatch = 10
	// Indexed Data Match refers to comparing content against a pre-compiled index of sensitive information to efficiently detect and prevent unauthorized access or breaches, streamlining DLP and compliance efforts.
	AnalyticTypeIndexedDataMatch = 11
	// The type is not mapped. See the type attribute, which contains a data source specific value.
	AnalyticTypeOther = 99
)

// AnalyticTypeName is the OCSF caption of a Analytic.type_id value. It is what the
// string sibling of the identifier has to carry.
func AnalyticTypeName(id int) string {
	switch id {
	case 0:
		return "Unknown"
	case 1:
		return "Rule"
	case 2:
		return "Behavioral"
	case 3:
		return "Statistical"
	case 4:
		return "Learning (ML/DL)"
	case 5:
		return "Fingerprinting"
	case 6:
		return "Tagging"
	case 7:
		return "Keyword Match"
	case 8:
		return "Regular Expressions"
	case 9:
		return "Exact Data Match"
	case 10:
		return "Partial Data Match"
	case 11:
		return "Indexed Data Match"
	case 99:
		return "Other"
	}
	return ""
}

// ComplianceFindingActivity values of ComplianceFinding.activity_id, from the OCSF schema.
const (
	// The event activity is unknown.
	ComplianceFindingActivityUnknown = 0
	// A finding was created.
	ComplianceFindingActivityCreate = 1
	// A finding was updated.
	ComplianceFindingActivityUpdate = 2
	// A finding was closed.
	ComplianceFindingActivityClose = 3
	// The event activity is not mapped. See the activity_name attribute, which contains a data source specific value.
	ComplianceFindingActivityOther = 99
)

// ComplianceFindingActivityName is the OCSF caption of a ComplianceFinding.activity_id value. It is what the
// string sibling of the identifier has to carry.
func ComplianceFindingActivityName(id int) string {
	switch id {
	case 0:
		return "Unknown"
	case 1:
		return "Create"
	case 2:
		return "Update"
	case 3:
		return "Close"
	case 99:
		return "Other"
	}
	return ""
}

// ComplianceFindingTypeUID values of ComplianceFinding.type_uid, from the OCSF schema.
const (
	ComplianceFindingTypeUIDUnknown = 200300
	// A finding was created.
	ComplianceFindingTypeUIDCreate = 200301
	// A finding was updated.
	ComplianceFindingTypeUIDUpdate = 200302
	// A finding was closed.
	ComplianceFindingTypeUIDClose = 200303
	ComplianceFindingTypeUIDOther = 200399
)

// ComplianceFindingTypeUIDName is the OCSF caption of a ComplianceFinding.type_uid value. It is what the
// string sibling of the identifier has to carry.
func ComplianceFindingTypeUIDName(id int) string {
	switch id {
	case 200300:
		return "Compliance Finding: Unknown"
	case 200301:
		return "Compliance Finding: Create"
	case 200302:
		return "Compliance Finding: Update"
	case 200303:
		return "Compliance Finding: Close"
	case 200399:
		return "Compliance Finding: Other"
	}
	return ""
}

// ComplianceStatus values of Compliance.status_id, from the OCSF schema.
const (
	// The status is unknown.
	ComplianceStatusUnknown = 0
	// The compliance check passed for all the evaluated resources.
	ComplianceStatusPass = 1
	// The compliance check did not yield a result due to missing information.
	ComplianceStatusWarning = 2
	// The compliance check failed for at least one of the evaluated resources.
	ComplianceStatusFail = 3
	// The event status is not mapped. See the status attribute, which contains a data source specific value.
	ComplianceStatusOther = 99
)

// ComplianceStatusName is the OCSF caption of a Compliance.status_id value. It is what the
// string sibling of the identifier has to carry.
func ComplianceStatusName(id int) string {
	switch id {
	case 0:
		return "Unknown"
	case 1:
		return "Pass"
	case 2:
		return "Warning"
	case 3:
		return "Fail"
	case 99:
		return "Other"
	}
	return ""
}

// DetectionFindingActivity values of DetectionFinding.activity_id, from the OCSF schema.
const (
	// The event activity is unknown.
	DetectionFindingActivityUnknown = 0
	// A finding was created.
	DetectionFindingActivityCreate = 1
	// A finding was updated.
	DetectionFindingActivityUpdate = 2
	// A finding was closed.
	DetectionFindingActivityClose = 3
	// The event activity is not mapped. See the activity_name attribute, which contains a data source specific value.
	DetectionFindingActivityOther = 99
)

// DetectionFindingActivityName is the OCSF caption of a DetectionFinding.activity_id value. It is what the
// string sibling of the identifier has to carry.
func DetectionFindingActivityName(id int) string {
	switch id {
	case 0:
		return "Unknown"
	case 1:
		return "Create"
	case 2:
		return "Update"
	case 3:
		return "Close"
	case 99:
		return "Other"
	}
	return ""
}

// DetectionFindingTypeUID values of DetectionFinding.type_uid, from the OCSF schema.
const (
	DetectionFindingTypeUIDUnknown = 200400
	// A finding was created.
	DetectionFindingTypeUIDCreate = 200401
	// A finding was updated.
	DetectionFindingTypeUIDUpdate = 200402
	// A finding was closed.
	DetectionFindingTypeUIDClose = 200403
	DetectionFindingTypeUIDOther = 200499
)

// DetectionFindingTypeUIDName is the OCSF caption of a DetectionFinding.type_uid value. It is what the
// string sibling of the identifier has to carry.
func DetectionFindingTypeUIDName(id int) string {
	switch id {
	case 200400:
		return "Detection Finding: Unknown"
	case 200401:
		return "Detection Finding: Create"
	case 200402:
		return "Detection Finding: Update"
	case 200403:
		return "Detection Finding: Close"
	case 200499:
		return "Detection Finding: Other"
	}
	return ""
}

// DeviceType values of Device.type_id, from the OCSF schema.
const (
	// The type is unknown.
	DeviceTypeUnknown = 0
	// A server.
	DeviceTypeServer = 1
	// A desktop computer.
	DeviceTypeDesktop = 2
	// A laptop computer.
	DeviceTypeLaptop = 3
	// A tablet computer.
	DeviceTypeTablet = 4
	// A mobile phone.
	DeviceTypeMobile = 5
	// A virtual machine.
	DeviceTypeVirtual = 6
	// An IOT (Internet of Things) device.
	DeviceTypeIOT = 7
	// A web browser.
	DeviceTypeBrowser = 8
	// A networking firewall.
	DeviceTypeFirewall = 9
	// A networking switch.
	DeviceTypeSwitch = 10
	// A networking hub.
	DeviceTypeHub = 11
	// A networking router.
	DeviceTypeRouter = 12
	// An intrusion detection system.
	DeviceTypeIDS = 13
	// An intrusion prevention system.
	DeviceTypeIPS = 14
	// A Load Balancer device.
	DeviceTypeLoadBalancer = 15
	// The type is not mapped. See the type attribute, which contains a data source specific value.
	DeviceTypeOther = 99
)

// DeviceTypeName is the OCSF caption of a Device.type_id value. It is what the
// string sibling of the identifier has to carry.
func DeviceTypeName(id int) string {
	switch id {
	case 0:
		return "Unknown"
	case 1:
		return "Server"
	case 2:
		return "Desktop"
	case 3:
		return "Laptop"
	case 4:
		return "Tablet"
	case 5:
		return "Mobile"
	case 6:
		return "Virtual"
	case 7:
		return "IOT"
	case 8:
		return "Browser"
	case 9:
		return "Firewall"
	case 10:
		return "Switch"
	case 11:
		return "Hub"
	case 12:
		return "Router"
	case 13:
		return "IDS"
	case 14:
		return "IPS"
	case 15:
		return "Load Balancer"
	case 99:
		return "Other"
	}
	return ""
}

// Impact values of impact_id, from the OCSF schema.
const (
	// The normalized impact is unknown.
	ImpactUnknown  = 0
	ImpactLow      = 1
	ImpactMedium   = 2
	ImpactHigh     = 3
	ImpactCritical = 4
	// The impact is not mapped. See the impact attribute, which contains a data source specific value.
	ImpactOther = 99
)

// ImpactName is the OCSF caption of a impact_id value. It is what the
// string sibling of the identifier has to carry.
func ImpactName(id int) string {
	switch id {
	case 0:
		return "Unknown"
	case 1:
		return "Low"
	case 2:
		return "Medium"
	case 3:
		return "High"
	case 4:
		return "Critical"
	case 99:
		return "Other"
	}
	return ""
}

// InventoryInfoActivity values of InventoryInfo.activity_id, from the OCSF schema.
const (
	// The event activity is unknown.
	InventoryInfoActivityUnknown = 0
	// The discovered information is via a log.
	InventoryInfoActivityLog = 1
	// The discovered information is via a collection process.
	InventoryInfoActivityCollect = 2
	// The event activity is not mapped. See the activity_name attribute, which contains a data source specific value.
	InventoryInfoActivityOther = 99
)

// InventoryInfoActivityName is the OCSF caption of a InventoryInfo.activity_id value. It is what the
// string sibling of the identifier has to carry.
func InventoryInfoActivityName(id int) string {
	switch id {
	case 0:
		return "Unknown"
	case 1:
		return "Log"
	case 2:
		return "Collect"
	case 99:
		return "Other"
	}
	return ""
}

// InventoryInfoTypeUID values of InventoryInfo.type_uid, from the OCSF schema.
const (
	InventoryInfoTypeUIDUnknown = 500100
	// The discovered information is via a log.
	InventoryInfoTypeUIDLog = 500101
	// The discovered information is via a collection process.
	InventoryInfoTypeUIDCollect = 500102
	InventoryInfoTypeUIDOther   = 500199
)

// InventoryInfoTypeUIDName is the OCSF caption of a InventoryInfo.type_uid value. It is what the
// string sibling of the identifier has to carry.
func InventoryInfoTypeUIDName(id int) string {
	switch id {
	case 500100:
		return "Device Inventory Info: Unknown"
	case 500101:
		return "Device Inventory Info: Log"
	case 500102:
		return "Device Inventory Info: Collect"
	case 500199:
		return "Device Inventory Info: Other"
	}
	return ""
}

// OSType values of OS.type_id, from the OCSF schema.
const (
	// The type is unknown.
	OSTypeUnknown = 0
	// The type is not mapped. See the type attribute, which contains a data source specific value.
	OSTypeOther         = 99
	OSTypeWindows       = 100
	OSTypeWindowsMobile = 101
	OSTypeLinux         = 200
	OSTypeAndroid       = 201
	OSTypeMacOS         = 300
	OSTypeIOS           = 301
	OSTypeIPadOS        = 302
	OSTypeSolaris       = 400
	OSTypeAIX           = 401
	OSTypeHPUX          = 402
)

// OSTypeName is the OCSF caption of a OS.type_id value. It is what the
// string sibling of the identifier has to carry.
func OSTypeName(id int) string {
	switch id {
	case 0:
		return "Unknown"
	case 99:
		return "Other"
	case 100:
		return "Windows"
	case 101:
		return "Windows Mobile"
	case 200:
		return "Linux"
	case 201:
		return "Android"
	case 300:
		return "macOS"
	case 301:
		return "iOS"
	case 302:
		return "iPadOS"
	case 400:
		return "Solaris"
	case 401:
		return "AIX"
	case 402:
		return "HP-UX"
	}
	return ""
}

// ObservableType values of Observable.type_id, from the OCSF schema.
const (
	// Unknown observable data type.
	ObservableTypeUnknown = 0
	// Observable by Dictionary Type.Unique name assigned to a device connected to a computer network. A domain name in general is an Internet address that can be resolved through the Domain Name System (DNS). For example: r2-d2.example.com.
	ObservableTypeHostname = 1
	// Observable by Dictionary Type.Internet Protocol address (IP address), in either IPv4 or IPv6 format. For example, 192.168.200.24 or 2001:0db8:85a3:0000:0000:8a2e:0370:7334.
	ObservableTypeIPAddress = 2
	// Observable by Dictionary Type.Media Access Control (MAC) address. For example: 18:36:F3:98:4F:9A.
	ObservableTypeMACAddress = 3
	// Observable by Dictionary Type.User name. For example: john_doe.
	ObservableTypeUserName = 4
	// Observable by Dictionary Type.Email address. For example: john_doe@example.com.
	ObservableTypeEmailAddress = 5
	// Observable by Dictionary Type.Uniform Resource Locator (URL) string. For example: http://www.example.com/download/trouble.exe.
	ObservableTypeURLString = 6
	// Observable by Dictionary Type.File name. For example: text-file.txt.
	ObservableTypeFileName = 7
	// Observable by Dictionary Type.Hash. A unique value that corresponds to the content of the file, image, ja3_hash or hassh found in the schema. For example MD5: 3172ac7e2b55cbb81f04a6e65855a628.
	ObservableTypeHash = 8
	// Observable by Dictionary Type.Process name. For example: Notepad.
	ObservableTypeProcessName = 9
	// Observable by Dictionary Type.Resource unique identifier. For example, S3 Bucket name or EC2 Instance ID.
	ObservableTypeResourceUID = 10
	// Observable by Dictionary Type.The TCP/UDP port number. For example: 80 or 22.
	ObservableTypePort = 11
	// Observable by Dictionary Type.The subnet represented in a CIDR notation, using the format network_address/prefix_length. The network_address can be in either IPv4 or IPv6 format. The prefix length indicates the number of bits used for the network portion, and the remaining bits are available for host addresses within that subnet. For example:192.168.1.0/242001:0db8:85a3:0000::/64
	ObservableTypeSubnet = 12
	// Observable by Dictionary Attribute.The full command line used to launch an application, service, process, or job. For example: ssh user@10.0.0.10. If the command line is unavailable or missing, the empty string '' is to be used.
	ObservableTypeCommandLine = 13
	// Observable by Dictionary Attribute.The ISO 3166-1 Alpha-2 country code. For the complete list of country codes see ISO 3166-1 alpha-2 codes. Note: The two letter country code should be capitalized. For example: US or CA.
	ObservableTypeCountry = 14
	// Observable by Dictionary Attribute.The process identifier, as reported by the operating system. Process ID (PID) is a number used by the operating system to uniquely identify an active process.
	ObservableTypeProcessID = 15
	// Observable by Dictionary Attribute.The request header that identifies the operating system and web browser.
	ObservableTypeHTTPUserAgent = 16
	// Observable by Object-Specific Attribute.Object-specific attribute "uid" for the CWE Object.
	ObservableTypeCWEObjectUID = 17
	// Observable by Object-Specific Attribute.Object-specific attribute "uid" for the CVE Object.
	ObservableTypeCVEObjectUID = 18
	// Observable by Dictionary Attribute.The unique identifier of the user's credential. For example, AWS Access Key ID.
	ObservableTypeUserCredentialID = 19
	// Observable by Object.The Endpoint object describes a physical or virtual device that connects to and exchanges information with a computer network. Some examples of endpoints are mobile devices, desktop computers, virtual machines, embedded devices, and servers. Internet-of-Things devices—like cameras, lighting, refrigerators, security systems, smart speakers, and thermostats—are also endpoints.
	ObservableTypeEndpoint = 20
	// Observable by Object.The User object describes the characteristics of a user/person or a security principal. Defined by D3FEND d3f:UserAccount.
	ObservableTypeUser = 21
	// Observable by Object.The Email object describes the email metadata such as sender, recipients, and direction. Defined by D3FEND d3f:Email.
	ObservableTypeEmail = 22
	// Observable by Object.The Uniform Resource Locator(URL) object describes the characteristics of a URL. Defined in RFC 1738 and by D3FEND d3f:URL.
	ObservableTypeUniformResourceLocator = 23
	// Observable by Object.The File object represents the metadata associated with a file stored in a computer system. It encompasses information about the file itself, including its attributes, properties, and organizational details. Defined by D3FEND d3f:File.
	ObservableTypeFile = 24
	// Observable by Object.The Process object describes a running instance of a launched program. Defined by D3FEND d3f:Process.
	ObservableTypeProcess = 25
	// Observable by Object.The Geo Location object describes a geographical location, usually associated with an IP address. Defined by D3FEND d3f:PhysicalLocation.
	ObservableTypeGeoLocation = 26
	// Observable by Object.The Container object describes an instance of a specific container. A container is a prepackaged, portable system image that runs isolated on an existing system using a container runtime like containerd.
	ObservableTypeContainer = 27
	// Observable by Object.The registry key object describes a Windows registry key. Defined by D3FEND d3f:WindowsRegistryKey.
	ObservableTypeRegistryKey = 28
	// Observable by Object.The registry value object describes a Windows registry value.
	ObservableTypeRegistryValue = 29
	// Observable by Object.The Fingerprint object provides detailed information about a digital fingerprint, which is a compact representation of data used to identify a longer piece of information, such as a public key or file content. It contains the algorithm and value of the fingerprint, enabling efficient and reliable identification of the associated data.
	ObservableTypeFingerprint = 30
	// The observable data type is not mapped. See the type attribute, which may contain data source specific value.
	ObservableTypeOther = 99
)

// ObservableTypeName is the OCSF caption of a Observable.type_id value. It is what the
// string sibling of the identifier has to carry.
func ObservableTypeName(id int) string {
	switch id {
	case 0:
		return "Unknown"
	case 1:
		return "Hostname"
	case 2:
		return "IP Address"
	case 3:
		return "MAC Address"
	case 4:
		return "User Name"
	case 5:
		return "Email Address"
	case 6:
		return "URL String"
	case 7:
		return "File Name"
	case 8:
		return "Hash"
	case 9:
		return "Process Name"
	case 10:
		return "Resource UID"
	case 11:
		return "Port"
	case 12:
		return "Subnet"
	case 13:
		return "Command Line"
	case 14:
		return "Country"
	case 15:
		return "Process ID"
	case 16:
		return "HTTP User-Agent"
	case 17:
		return "CWE Object: uid"
	case 18:
		return "CVE Object: uid"
	case 19:
		return "User Credential ID"
	case 20:
		return "Endpoint"
	case 21:
		return "User"
	case 22:
		return "Email"
	case 23:
		return "Uniform Resource Locator"
	case 24:
		return "File"
	case 25:
		return "Process"
	case 26:
		return "Geo Location"
	case 27:
		return "Container"
	case 28:
		return "Registry Key"
	case 29:
		return "Registry Value"
	case 30:
		return "Fingerprint"
	case 99:
		return "Other"
	}
	return ""
}

// RiskLevel values of risk_level_id, from the OCSF schema.
const (
	RiskLevelInfo     = 0
	RiskLevelLow      = 1
	RiskLevelMedium   = 2
	RiskLevelHigh     = 3
	RiskLevelCritical = 4
	// The risk level is not mapped. See the risk_level attribute, which contains a data source specific value.
	RiskLevelOther = 99
)

// RiskLevelName is the OCSF caption of a risk_level_id value. It is what the
// string sibling of the identifier has to carry.
func RiskLevelName(id int) string {
	switch id {
	case 0:
		return "Info"
	case 1:
		return "Low"
	case 2:
		return "Medium"
	case 3:
		return "High"
	case 4:
		return "Critical"
	case 99:
		return "Other"
	}
	return ""
}

// Severity values of severity_id, from the OCSF schema.
const (
	// The event/finding severity is unknown.
	SeverityUnknown = 0
	// Informational message. No action required.
	SeverityInformational = 1
	// The user decides if action is needed.
	SeverityLow = 2
	// Action is required but the situation is not serious at this time.
	SeverityMedium = 3
	// Action is required immediately.
	SeverityHigh = 4
	// Action is required immediately and the scope is broad.
	SeverityCritical = 5
	// An error occurred but it is too late to take remedial action.
	SeverityFatal = 6
	// The event/finding severity is not mapped. See the severity attribute, which contains a data source specific value.
	SeverityOther = 99
)

// SeverityName is the OCSF caption of a severity_id value. It is what the
// string sibling of the identifier has to carry.
func SeverityName(id int) string {
	switch id {
	case 0:
		return "Unknown"
	case 1:
		return "Informational"
	case 2:
		return "Low"
	case 3:
		return "Medium"
	case 4:
		return "High"
	case 5:
		return "Critical"
	case 6:
		return "Fatal"
	case 99:
		return "Other"
	}
	return ""
}

// Status values of status_id, from the OCSF schema.
const (
	// The status is unknown.
	StatusUnknown = 0
	// The Finding is new and yet to be reviewed.
	StatusNew = 1
	// The Finding is under review.
	StatusInProgress = 2
	// The Finding was reviewed, determined to be benign or a false positive and is now suppressed.
	StatusSuppressed = 3
	// The Finding was reviewed, remediated and is now considered resolved.
	StatusResolved = 4
	// The event status is not mapped. See the status attribute, which contains a data source specific value.
	StatusOther = 99
)

// StatusName is the OCSF caption of a status_id value. It is what the
// string sibling of the identifier has to carry.
func StatusName(id int) string {
	switch id {
	case 0:
		return "Unknown"
	case 1:
		return "New"
	case 2:
		return "In Progress"
	case 3:
		return "Suppressed"
	case 4:
		return "Resolved"
	case 99:
		return "Other"
	}
	return ""
}

// VulnerabilityFindingActivity values of VulnerabilityFinding.activity_id, from the OCSF schema.
const (
	// The event activity is unknown.
	VulnerabilityFindingActivityUnknown = 0
	// A finding was created.
	VulnerabilityFindingActivityCreate = 1
	// A finding was updated.
	VulnerabilityFindingActivityUpdate = 2
	// A finding was closed.
	VulnerabilityFindingActivityClose = 3
	// The event activity is not mapped. See the activity_name attribute, which contains a data source specific value.
	VulnerabilityFindingActivityOther = 99
)

// VulnerabilityFindingActivityName is the OCSF caption of a VulnerabilityFinding.activity_id value. It is what the
// string sibling of the identifier has to carry.
func VulnerabilityFindingActivityName(id int) string {
	switch id {
	case 0:
		return "Unknown"
	case 1:
		return "Create"
	case 2:
		return "Update"
	case 3:
		return "Close"
	case 99:
		return "Other"
	}
	return ""
}

// VulnerabilityFindingTypeUID values of VulnerabilityFinding.type_uid, from the OCSF schema.
const (
	VulnerabilityFindingTypeUIDUnknown = 200200
	// A finding was created.
	VulnerabilityFindingTypeUIDCreate = 200201
	// A finding was updated.
	VulnerabilityFindingTypeUIDUpdate = 200202
	// A finding was closed.
	VulnerabilityFindingTypeUIDClose = 200203
	VulnerabilityFindingTypeUIDOther = 200299
)

// VulnerabilityFindingTypeUIDName is the OCSF caption of a VulnerabilityFinding.type_uid value. It is what the
// string sibling of the identifier has to carry.
func VulnerabilityFindingTypeUIDName(id int) string {
	switch id {
	case 200200:
		return "Vulnerability Finding: Unknown"
	case 200201:
		return "Vulnerability Finding: Create"
	case 200202:
		return "Vulnerability Finding: Update"
	case 200203:
		return "Vulnerability Finding: Close"
	case 200299:
		return "Vulnerability Finding: Other"
	}
	return ""
}
