// Copyright Mondoo, Inc. 2024, 2026
// SPDX-License-Identifier: BUSL-1.1

// Code generated by reports/ocsf/internal/gen from the compiled OCSF
// schemas in schemas/ and the attribute list in gen.yaml. DO NOT EDIT.

package ocsf

// ComplianceFinding is OCSF class 2003, Compliance Finding.
//
// Compliance Finding events describe results of evaluations performed against
// resources, to check compliance with various Industry Frameworks or Security
// Standards such as NIST SP 800-53, CIS AWS Foundations Benchmark v1.4.0,
// ISO/IEC 27001 etc.
type ComplianceFinding struct {
	// Activity ID
	//
	// The normalized identifier of the finding activity.
	ActivityID int `json:"activity_id" parquet:"activity_id"`

	// Activity
	//
	// The finding activity name, as defined by the activity_id.
	ActivityName string `json:"activity_name,omitempty" parquet:"activity_name,optional"`

	// Category ID
	//
	// The category unique identifier of the event.
	CategoryUID int `json:"category_uid" parquet:"category_uid"`

	// Category
	//
	// The event category name, as defined by category_uid value: Findings.
	CategoryName string `json:"category_name,omitempty" parquet:"category_name,optional"`

	// Class ID
	//
	// The unique identifier of a class. A class describes the attributes
	// available in an event.
	ClassUID int `json:"class_uid" parquet:"class_uid"`

	// Class
	//
	// The event class name, as defined by class_uid value: Compliance Finding.
	ClassName string `json:"class_name,omitempty" parquet:"class_name,optional"`

	// Type ID
	//
	// The event/finding type ID. It identifies the event's semantics and
	// structure. The value is calculated by the logging system as: class_uid *
	// 100 + activity_id.
	TypeUID int64 `json:"type_uid" parquet:"type_uid"`

	// Type Name
	//
	// The event/finding type name, as defined by the type_uid.
	TypeName string `json:"type_name,omitempty" parquet:"type_name,optional"`

	// Event Time
	//
	// The normalized event occurrence time or the finding creation time.
	Time int64 `json:"time" parquet:"time"`

	// Severity ID
	//
	// The normalized identifier of the event/finding severity.The normalized
	// severity is a measurement the effort and expense required to manage and
	// resolve an event or incident. Smaller numerical values represent lower
	// impact events, and larger numerical values represent higher impact
	// events.
	SeverityID int `json:"severity_id" parquet:"severity_id"`

	// Severity
	//
	// The event/finding severity, normalized to the caption of the severity_id
	// value. In the case of 'Other', it is defined by the source.
	Severity string `json:"severity,omitempty" parquet:"severity,optional"`

	// Status ID
	//
	// The normalized status identifier of the Finding, set by the consumer.
	StatusID int `json:"status_id" parquet:"status_id,optional"`

	// Status
	//
	// The normalized status of the Finding set by the consumer normalized to
	// the caption of the status_id value. In the case of 'Other', it is
	// defined by the source.
	Status string `json:"status,omitempty" parquet:"status,optional"`

	// Status Code
	//
	// The event status code, as reported by the event source.For example, in a
	// Windows Failed Authentication event, this would be the value of 'Failure
	// Code', e.g. 0x18.
	StatusCode string `json:"status_code,omitempty" parquet:"status_code,optional"`

	// Status Detail
	//
	// The status detail contains additional information about the
	// event/finding outcome.
	StatusDetail string `json:"status_detail,omitempty" parquet:"status_detail,optional"`

	// Message
	//
	// The description of the event/finding, as defined by the source.
	Message string `json:"message,omitempty" parquet:"message,optional"`

	// Metadata
	//
	// The metadata associated with the event or a finding.
	Metadata Metadata `json:"metadata" parquet:"metadata"`

	// Unmapped Data
	//
	// The attributes that are not mapped to the event schema. The names and
	// values of those attributes are specific to the event source.
	Unmapped map[string]string `json:"unmapped,omitempty" parquet:"unmapped"`

	// Compliance
	//
	// The compliance object provides context to compliance findings (e.g., a
	// check against a specific regulatory or best practice framework such as
	// CIS, NIST etc.) and contains compliance related details.
	Compliance Compliance `json:"compliance" parquet:"compliance"`

	// Finding Information
	//
	// Describes the supporting information about a generated finding.
	FindingInfo FindingInfo `json:"finding_info" parquet:"finding_info"`

	// Remediation Guidance
	//
	// Describes the recommended remediation steps to address identified
	// issue(s).
	Remediation *Remediation `json:"remediation,omitempty" parquet:"remediation,optional"`

	// Resources Array
	//
	// Describes details about the resource/resouces that are the subject of
	// the compliance check.
	Resources []ResourceDetails `json:"resources,omitempty" parquet:"resources,list"`

	// Device (OCSF host profile)
	//
	// Describes the affected device/host. It can be used in conjunction with
	// Affected Resource(s). e.g. Specific details about an AWS EC2 instance,
	// that is affected by the Finding.
	Device *Device `json:"device,omitempty" parquet:"device,optional"`

	// Cloud (OCSF cloud profile)
	//
	// Describes details about the Cloud environment where the event was
	// originally created or logged.
	Cloud *Cloud `json:"cloud,omitempty" parquet:"cloud,optional"`
}

// NewComplianceFinding returns a ComplianceFinding with its classification
// attributes filled in from the schema. Pass one of the ComplianceFindingActivity
// constants.
func NewComplianceFinding(activityID int) ComplianceFinding {
	typeUID := ClassUIDComplianceFinding*100 + activityID
	return ComplianceFinding{
		ActivityID:   activityID,
		ActivityName: ComplianceFindingActivityName(activityID),
		CategoryUID:  CategoryUIDComplianceFinding,
		CategoryName: CategoryNameComplianceFinding,
		ClassUID:     ClassUIDComplianceFinding,
		ClassName:    ClassNameComplianceFinding,
		TypeUID:      int64(typeUID),
		TypeName:     ComplianceFindingTypeUIDName(typeUID),
	}
}

// DetectionFinding is OCSF class 2004, Detection Finding.
//
// A Detection Finding describes detections or alerts generated by security
// products using correlation engines, detection engines or other
// methodologies. Note: if the product is a security control, the
// security_control profile should be applied and its attacks information
// should be duplicated into the finding_info object.
type DetectionFinding struct {
	// Activity ID
	//
	// The normalized identifier of the finding activity.
	ActivityID int `json:"activity_id" parquet:"activity_id"`

	// Activity
	//
	// The finding activity name, as defined by the activity_id.
	ActivityName string `json:"activity_name,omitempty" parquet:"activity_name,optional"`

	// Category ID
	//
	// The category unique identifier of the event.
	CategoryUID int `json:"category_uid" parquet:"category_uid"`

	// Category
	//
	// The event category name, as defined by category_uid value: Findings.
	CategoryName string `json:"category_name,omitempty" parquet:"category_name,optional"`

	// Class ID
	//
	// The unique identifier of a class. A class describes the attributes
	// available in an event.
	ClassUID int `json:"class_uid" parquet:"class_uid"`

	// Class
	//
	// The event class name, as defined by class_uid value: Detection Finding.
	ClassName string `json:"class_name,omitempty" parquet:"class_name,optional"`

	// Type ID
	//
	// The event/finding type ID. It identifies the event's semantics and
	// structure. The value is calculated by the logging system as: class_uid *
	// 100 + activity_id.
	TypeUID int64 `json:"type_uid" parquet:"type_uid"`

	// Type Name
	//
	// The event/finding type name, as defined by the type_uid.
	TypeName string `json:"type_name,omitempty" parquet:"type_name,optional"`

	// Event Time
	//
	// The normalized event occurrence time or the finding creation time.
	Time int64 `json:"time" parquet:"time"`

	// Severity ID
	//
	// The normalized identifier of the event/finding severity.The normalized
	// severity is a measurement the effort and expense required to manage and
	// resolve an event or incident. Smaller numerical values represent lower
	// impact events, and larger numerical values represent higher impact
	// events.
	SeverityID int `json:"severity_id" parquet:"severity_id"`

	// Severity
	//
	// The event/finding severity, normalized to the caption of the severity_id
	// value. In the case of 'Other', it is defined by the source.
	Severity string `json:"severity,omitempty" parquet:"severity,optional"`

	// Status ID
	//
	// The normalized status identifier of the Finding, set by the consumer.
	StatusID int `json:"status_id" parquet:"status_id,optional"`

	// Status
	//
	// The normalized status of the Finding set by the consumer normalized to
	// the caption of the status_id value. In the case of 'Other', it is
	// defined by the source.
	Status string `json:"status,omitempty" parquet:"status,optional"`

	// Status Code
	//
	// The event status code, as reported by the event source.For example, in a
	// Windows Failed Authentication event, this would be the value of 'Failure
	// Code', e.g. 0x18.
	StatusCode string `json:"status_code,omitempty" parquet:"status_code,optional"`

	// Status Detail
	//
	// The status detail contains additional information about the
	// event/finding outcome.
	StatusDetail string `json:"status_detail,omitempty" parquet:"status_detail,optional"`

	// Message
	//
	// The description of the event/finding, as defined by the source.
	Message string `json:"message,omitempty" parquet:"message,optional"`

	// Metadata
	//
	// The metadata associated with the event or a finding.
	Metadata Metadata `json:"metadata" parquet:"metadata"`

	// Unmapped Data
	//
	// The attributes that are not mapped to the event schema. The names and
	// values of those attributes are specific to the event source.
	Unmapped map[string]string `json:"unmapped,omitempty" parquet:"unmapped"`

	// Finding Information
	//
	// Describes the supporting information about a generated finding.
	FindingInfo FindingInfo `json:"finding_info" parquet:"finding_info"`

	// Risk Score
	//
	// The risk score as reported by the event source.
	RiskScore int `json:"risk_score,omitempty" parquet:"risk_score,optional"`

	// Risk Level ID
	//
	// The normalized risk level id.
	RiskLevelID int `json:"risk_level_id" parquet:"risk_level_id,optional"`

	// Risk Level
	//
	// The risk level, normalized to the caption of the risk_level_id value.
	RiskLevel string `json:"risk_level,omitempty" parquet:"risk_level,optional"`

	// Impact ID
	//
	// The normalized impact of the finding.
	ImpactID int `json:"impact_id" parquet:"impact_id,optional"`

	// Impact
	//
	// The impact , normalized to the caption of the impact_id value. In the
	// case of 'Other', it is defined by the event source.
	Impact string `json:"impact,omitempty" parquet:"impact,optional"`

	// Impact
	//
	// The impact of the finding, valid range 0-100.
	ImpactScore int `json:"impact_score,omitempty" parquet:"impact_score,optional"`

	// Remediation Guidance
	//
	// Describes the recommended remediation steps to address identified
	// issue(s).
	Remediation *Remediation `json:"remediation,omitempty" parquet:"remediation,optional"`

	// Affected Resources
	//
	// Describes details about resources that were the target of the activity
	// that triggered the finding.
	Resources []ResourceDetails `json:"resources,omitempty" parquet:"resources,list"`

	// Device (OCSF host profile)
	//
	// Describes the affected device/host. It can be used in conjunction with
	// Affected Resource(s). e.g. Specific details about an AWS EC2 instance,
	// that is affected by the Finding.
	Device *Device `json:"device,omitempty" parquet:"device,optional"`

	// Cloud (OCSF cloud profile)
	//
	// Describes details about the Cloud environment where the event was
	// originally created or logged.
	Cloud *Cloud `json:"cloud,omitempty" parquet:"cloud,optional"`
}

// NewDetectionFinding returns a DetectionFinding with its classification
// attributes filled in from the schema. Pass one of the DetectionFindingActivity
// constants.
func NewDetectionFinding(activityID int) DetectionFinding {
	typeUID := ClassUIDDetectionFinding*100 + activityID
	return DetectionFinding{
		ActivityID:   activityID,
		ActivityName: DetectionFindingActivityName(activityID),
		CategoryUID:  CategoryUIDDetectionFinding,
		CategoryName: CategoryNameDetectionFinding,
		ClassUID:     ClassUIDDetectionFinding,
		ClassName:    ClassNameDetectionFinding,
		TypeUID:      int64(typeUID),
		TypeName:     DetectionFindingTypeUIDName(typeUID),
	}
}

// InventoryInfo is OCSF class 5001, Device Inventory Info.
//
// Device Inventory Info events report device inventory data that is either
// logged or proactively collected. For example, when collecting device
// information from a CMDB or running a network sweep of connected devices.
type InventoryInfo struct {
	// Activity ID
	//
	// The normalized identifier of the activity that triggered the event.
	ActivityID int `json:"activity_id" parquet:"activity_id"`

	// Activity
	//
	// The event activity name, as defined by the activity_id.
	ActivityName string `json:"activity_name,omitempty" parquet:"activity_name,optional"`

	// Category ID
	//
	// The category unique identifier of the event.
	CategoryUID int `json:"category_uid" parquet:"category_uid"`

	// Category
	//
	// The event category name, as defined by category_uid value: Discovery.
	CategoryName string `json:"category_name,omitempty" parquet:"category_name,optional"`

	// Class ID
	//
	// The unique identifier of a class. A class describes the attributes
	// available in an event.
	ClassUID int `json:"class_uid" parquet:"class_uid"`

	// Class
	//
	// The event class name, as defined by class_uid value: Device Inventory
	// Info.
	ClassName string `json:"class_name,omitempty" parquet:"class_name,optional"`

	// Type ID
	//
	// The event/finding type ID. It identifies the event's semantics and
	// structure. The value is calculated by the logging system as: class_uid *
	// 100 + activity_id.
	TypeUID int64 `json:"type_uid" parquet:"type_uid"`

	// Type Name
	//
	// The event/finding type name, as defined by the type_uid.
	TypeName string `json:"type_name,omitempty" parquet:"type_name,optional"`

	// Event Time
	//
	// The normalized event occurrence time or the finding creation time.
	Time int64 `json:"time" parquet:"time"`

	// Severity ID
	//
	// The normalized identifier of the event/finding severity.The normalized
	// severity is a measurement the effort and expense required to manage and
	// resolve an event or incident. Smaller numerical values represent lower
	// impact events, and larger numerical values represent higher impact
	// events.
	SeverityID int `json:"severity_id" parquet:"severity_id"`

	// Severity
	//
	// The event/finding severity, normalized to the caption of the severity_id
	// value. In the case of 'Other', it is defined by the source.
	Severity string `json:"severity,omitempty" parquet:"severity,optional"`

	// Message
	//
	// The description of the event/finding, as defined by the source.
	Message string `json:"message,omitempty" parquet:"message,optional"`

	// Metadata
	//
	// The metadata associated with the event or a finding.
	Metadata Metadata `json:"metadata" parquet:"metadata"`

	// Unmapped Data
	//
	// The attributes that are not mapped to the event schema. The names and
	// values of those attributes are specific to the event source.
	Unmapped map[string]string `json:"unmapped,omitempty" parquet:"unmapped"`

	// Device
	//
	// The device that is being discovered by an inventory process.
	Device Device `json:"device" parquet:"device"`

	// Cloud (OCSF cloud profile)
	//
	// Describes details about the Cloud environment where the event was
	// originally created or logged.
	Cloud *Cloud `json:"cloud,omitempty" parquet:"cloud,optional"`
}

// NewInventoryInfo returns a InventoryInfo with its classification
// attributes filled in from the schema. Pass one of the InventoryInfoActivity
// constants.
func NewInventoryInfo(activityID int) InventoryInfo {
	typeUID := ClassUIDInventoryInfo*100 + activityID
	return InventoryInfo{
		ActivityID:   activityID,
		ActivityName: InventoryInfoActivityName(activityID),
		CategoryUID:  CategoryUIDInventoryInfo,
		CategoryName: CategoryNameInventoryInfo,
		ClassUID:     ClassUIDInventoryInfo,
		ClassName:    ClassNameInventoryInfo,
		TypeUID:      int64(typeUID),
		TypeName:     InventoryInfoTypeUIDName(typeUID),
	}
}

// VulnerabilityFinding is OCSF class 2002, Vulnerability Finding.
//
// The Vulnerability Finding event is a notification about weakness in an
// information system, system security procedures, internal controls, or
// implementation that could be exploited or triggered by a threat source.
type VulnerabilityFinding struct {
	// Activity ID
	//
	// The normalized identifier of the finding activity.
	ActivityID int `json:"activity_id" parquet:"activity_id"`

	// Activity
	//
	// The finding activity name, as defined by the activity_id.
	ActivityName string `json:"activity_name,omitempty" parquet:"activity_name,optional"`

	// Category ID
	//
	// The category unique identifier of the event.
	CategoryUID int `json:"category_uid" parquet:"category_uid"`

	// Category
	//
	// The event category name, as defined by category_uid value: Findings.
	CategoryName string `json:"category_name,omitempty" parquet:"category_name,optional"`

	// Class ID
	//
	// The unique identifier of a class. A class describes the attributes
	// available in an event.
	ClassUID int `json:"class_uid" parquet:"class_uid"`

	// Class
	//
	// The event class name, as defined by class_uid value: Vulnerability
	// Finding.
	ClassName string `json:"class_name,omitempty" parquet:"class_name,optional"`

	// Type ID
	//
	// The event/finding type ID. It identifies the event's semantics and
	// structure. The value is calculated by the logging system as: class_uid *
	// 100 + activity_id.
	TypeUID int64 `json:"type_uid" parquet:"type_uid"`

	// Type Name
	//
	// The event/finding type name, as defined by the type_uid.
	TypeName string `json:"type_name,omitempty" parquet:"type_name,optional"`

	// Event Time
	//
	// The normalized event occurrence time or the finding creation time.
	Time int64 `json:"time" parquet:"time"`

	// Severity ID
	//
	// The normalized identifier of the event/finding severity.The normalized
	// severity is a measurement the effort and expense required to manage and
	// resolve an event or incident. Smaller numerical values represent lower
	// impact events, and larger numerical values represent higher impact
	// events.
	SeverityID int `json:"severity_id" parquet:"severity_id"`

	// Severity
	//
	// The event/finding severity, normalized to the caption of the severity_id
	// value. In the case of 'Other', it is defined by the source.
	Severity string `json:"severity,omitempty" parquet:"severity,optional"`

	// Status ID
	//
	// The normalized status identifier of the Finding, set by the consumer.
	StatusID int `json:"status_id" parquet:"status_id,optional"`

	// Status
	//
	// The normalized status of the Finding set by the consumer normalized to
	// the caption of the status_id value. In the case of 'Other', it is
	// defined by the source.
	Status string `json:"status,omitempty" parquet:"status,optional"`

	// Status Code
	//
	// The event status code, as reported by the event source.For example, in a
	// Windows Failed Authentication event, this would be the value of 'Failure
	// Code', e.g. 0x18.
	StatusCode string `json:"status_code,omitempty" parquet:"status_code,optional"`

	// Message
	//
	// The description of the event/finding, as defined by the source.
	Message string `json:"message,omitempty" parquet:"message,optional"`

	// Metadata
	//
	// The metadata associated with the event or a finding.
	Metadata Metadata `json:"metadata" parquet:"metadata"`

	// Unmapped Data
	//
	// The attributes that are not mapped to the event schema. The names and
	// values of those attributes are specific to the event source.
	Unmapped map[string]string `json:"unmapped,omitempty" parquet:"unmapped"`

	// Finding Information
	//
	// Describes the supporting information about a generated finding.
	FindingInfo FindingInfo `json:"finding_info" parquet:"finding_info"`

	// Vulnerabilities
	//
	// This object describes vulnerabilities reported in a security finding.
	Vulnerabilities []Vulnerability `json:"vulnerabilities,omitempty" parquet:"vulnerabilities,list"`

	// Affected Resources
	//
	// Describes details about the resource/resources that are affected by the
	// vulnerability/vulnerabilities.
	Resources []ResourceDetails `json:"resources,omitempty" parquet:"resources,list"`

	// Device (OCSF host profile)
	//
	// Describes the affected device/host. It can be used in conjunction with
	// Affected Resource(s). e.g. Specific details about an AWS EC2 instance,
	// that is affected by the Finding.
	Device *Device `json:"device,omitempty" parquet:"device,optional"`

	// Cloud (OCSF cloud profile)
	//
	// Describes details about the Cloud environment where the event was
	// originally created or logged.
	Cloud *Cloud `json:"cloud,omitempty" parquet:"cloud,optional"`
}

// NewVulnerabilityFinding returns a VulnerabilityFinding with its classification
// attributes filled in from the schema. Pass one of the VulnerabilityFindingActivity
// constants.
func NewVulnerabilityFinding(activityID int) VulnerabilityFinding {
	typeUID := ClassUIDVulnerabilityFinding*100 + activityID
	return VulnerabilityFinding{
		ActivityID:   activityID,
		ActivityName: VulnerabilityFindingActivityName(activityID),
		CategoryUID:  CategoryUIDVulnerabilityFinding,
		CategoryName: CategoryNameVulnerabilityFinding,
		ClassUID:     ClassUIDVulnerabilityFinding,
		ClassName:    ClassNameVulnerabilityFinding,
		TypeUID:      int64(typeUID),
		TypeName:     VulnerabilityFindingTypeUIDName(typeUID),
	}
}

// Account is the OCSF Account object.
//
// The Account object contains details about the account that initiated or
// performed a specific activity within a system or application.
type Account struct {
	// Unique ID
	//
	// The unique identifier of the account (e.g. AWS Account ID).
	UID string `json:"uid,omitempty" parquet:"uid,optional"`

	// Name
	//
	// The name of the account (e.g. GCP Account Name).
	Name string `json:"name,omitempty" parquet:"name,optional"`

	// Type
	//
	// The account type, normalized to the caption of 'account_type_id'. In the
	// case of 'Other', it is defined by the event source.
	Type string `json:"type,omitempty" parquet:"type,optional"`
}

// Advisory is the OCSF Advisory object.
//
// The Advisory object represents publicly disclosed cybersecurity
// vulnerabilities defined in a Security advisory. e.g. Microsoft KB Article,
// Apple Security Advisory, or a GitHub Security Advisory (GHSA)
//
// Only in OCSF 1.9.0.
type Advisory struct {
	// Advisory ID
	//
	// The unique identifier assigned to the advisory or disclosed
	// vulnerability, e.g, GHSA-5mrr-rgp6-x4gr.
	//
	// Only in OCSF 1.9.0; empty otherwise.
	UID string `json:"uid" parquet:"uid"`

	// Title
	//
	// A title or a brief phrase summarizing the Advisory.
	//
	// Only in OCSF 1.9.0; empty otherwise.
	Title string `json:"title,omitempty" parquet:"title,optional"`

	// Description
	//
	// A brief description of the Advisory Record.
	//
	// Only in OCSF 1.9.0; empty otherwise.
	Desc string `json:"desc,omitempty" parquet:"desc,optional"`

	// References
	//
	// A list of reference URLs with additional information about the
	// vulnerabilities disclosed in the Advisory.
	//
	// Only in OCSF 1.9.0; empty otherwise.
	References []string `json:"references,omitempty" parquet:"references,list"`
}

// AffectedPackage is the OCSF Affected Software Package object.
//
// The Affected Package object describes details about a software package
// identified as affected by a vulnerability/vulnerabilities.
type AffectedPackage struct {
	// Name
	//
	// The software package name.
	Name string `json:"name" parquet:"name"`

	// Version
	//
	// The software package version.
	Version string `json:"version" parquet:"version"`

	// Architecture
	//
	// Architecture is a shorthand name describing the type of computer
	// hardware the packaged software is meant to run on.
	Architecture string `json:"architecture,omitempty" parquet:"architecture,optional"`

	// Package URL
	//
	// A purl is a URL string used to identify and locate a software package in
	// a mostly universal and uniform way across programming languages, package
	// managers, packaging conventions, tools, APIs and databases.
	PURL string `json:"purl,omitempty" parquet:"purl,optional"`

	// Fixed In Version
	//
	// The software package version in which a reported vulnerability was
	// patched/fixed.
	FixedInVersion string `json:"fixed_in_version,omitempty" parquet:"fixed_in_version,optional"`

	// Package Manager
	//
	// The software packager manager utilized to manage a package on a system,
	// e.g. npm, yum, dpkg etc.
	PackageManager string `json:"package_manager,omitempty" parquet:"package_manager,optional"`
}

// Analytic is the OCSF Analytic object.
//
// The Analytic object contains details about the analytic technique used to
// analyze and derive insights from the data or information that led to the
// creation of a finding or conclusion.
type Analytic struct {
	// Type ID
	//
	// The analytic type ID.
	TypeID int `json:"type_id" parquet:"type_id"`

	// Type
	//
	// The analytic type.
	Type string `json:"type,omitempty" parquet:"type,optional"`

	// Name
	//
	// The name of the analytic that generated the finding.
	Name string `json:"name,omitempty" parquet:"name,optional"`

	// Unique ID
	//
	// The unique identifier of the analytic that generated the finding.
	UID string `json:"uid,omitempty" parquet:"uid,optional"`

	// Description
	//
	// The description of the analytic that generated the finding.
	Desc string `json:"desc,omitempty" parquet:"desc,optional"`

	// Category
	//
	// The analytic category.
	Category string `json:"category,omitempty" parquet:"category,optional"`

	// Version
	//
	// The analytic version. For example: 1.1.
	Version string `json:"version,omitempty" parquet:"version,optional"`
}

// Cloud is the OCSF Cloud object.
//
// The Cloud object contains information about a cloud account such as AWS
// Account ID, regions, etc.
type Cloud struct {
	// Provider
	//
	// The unique name of the Cloud services provider, such as AWS, MS Azure,
	// GCP, etc.
	Provider string `json:"provider" parquet:"provider"`

	// Account
	//
	// The account object describes details about the account that was the
	// source or target of the activity.
	Account *Account `json:"account,omitempty" parquet:"account,optional"`

	// Region
	//
	// The name of the cloud region, as defined by the cloud provider.
	Region string `json:"region,omitempty" parquet:"region,optional"`

	// Network Zone
	//
	// The availability zone in the cloud region, as defined by the cloud
	// provider.
	Zone string `json:"zone,omitempty" parquet:"zone,optional"`

	// Project ID
	//
	// The unique identifier of a Cloud project.
	ProjectUID string `json:"project_uid,omitempty" parquet:"project_uid,optional"`
}

// Compliance is the OCSF Compliance object.
//
// The Compliance object contains information about Industry and Regulatory
// Framework standards, controls and requirements.
type Compliance struct {
	// Security Standards
	//
	// Security standards are a set of criteria organizations can follow to
	// protect sensitive and confidential information. e.g. NIST SP 800-53, CIS
	// AWS Foundations Benchmark v1.4.0, ISO/IEC 27001
	Standards []string `json:"standards,omitempty" parquet:"standards,list"`

	// Security Control
	//
	// A Control is prescriptive, prioritized, and simplified set of best
	// practices that one can use to strengthen their cybersecurity posture.
	// e.g. AWS SecurityHub Controls, CIS Controls.
	Control string `json:"control,omitempty" parquet:"control,optional"`

	// Compliance Requirements
	//
	// A list of requirements associated to a specific control in an industry
	// or regulatory framework. e.g. NIST.800-53.r5 AU-10
	Requirements []string `json:"requirements,omitempty" parquet:"requirements,list"`

	// Status
	//
	// The resultant status of the compliance check normalized to the caption
	// of the status_id value. In the case of 'Other', it is defined by the
	// event source.
	Status string `json:"status,omitempty" parquet:"status,optional"`

	// Status ID
	//
	// The normalized status identifier of the compliance check.
	StatusID int `json:"status_id" parquet:"status_id,optional"`

	// Status Code
	//
	// The resultant status code of the compliance check.
	StatusCode string `json:"status_code,omitempty" parquet:"status_code,optional"`

	// Status Detail
	//
	// The contextual description of the status, status_code values.
	StatusDetail string `json:"status_detail,omitempty" parquet:"status_detail,optional"`

	// Status Details
	//
	// A list of contextual descriptions of the status, status_code values.
	//
	// Only in OCSF 1.9.0; empty otherwise.
	StatusDetails []string `json:"status_details,omitempty" parquet:"status_details,list"`

	// Category
	//
	// The category a control framework pertains to, as reported by the source
	// tool, such as Asset Management or Risk Assessment.
	//
	// Only in OCSF 1.9.0; empty otherwise.
	Category string `json:"category,omitempty" parquet:"category,optional"`

	// Description
	//
	// The description or criteria of a control.
	//
	// Only in OCSF 1.9.0; empty otherwise.
	Desc string `json:"desc,omitempty" parquet:"desc,optional"`
}

// CPUInfo is the OCSF CPU Information object.
//
// The CPU information object contains attributes describing a physical CPU
// package installed in the device.
//
// Only in OCSF 1.9.0.
type CPUInfo struct {
	// CPU Architecture
	//
	// The CPU architecture, normalized to the caption of the
	// cpu_architecture_id value. In the case of Other, it is defined by the
	// source.
	//
	// Only in OCSF 1.9.0; empty otherwise.
	CPUArchitecture string `json:"cpu_architecture,omitempty" parquet:"cpu_architecture,optional"`
}

// CVE is the OCSF CVE object.
//
// The Common Vulnerabilities and Exposures (CVE) object represents publicly
// disclosed cybersecurity vulnerabilities defined in CVE Program catalog
// (CVE). There is one CVE Record for each vulnerability in the catalog.
type CVE struct {
	// CVE ID
	//
	// The Common Vulnerabilities and Exposures unique number assigned to a
	// specific computer vulnerability. A CVE Identifier begins with 4 digits
	// representing the year followed by a sequence of digits that acts as a
	// unique identifier. For example: CVE-2021-12345.
	UID string `json:"uid" parquet:"uid"`

	// Title
	//
	// A title or a brief phrase summarizing the CVE record.
	Title string `json:"title,omitempty" parquet:"title,optional"`

	// Description
	//
	// A brief description of the CVE Record.
	Desc string `json:"desc,omitempty" parquet:"desc,optional"`

	// Created Time
	//
	// The Record Creation Date identifies when the CVE ID was issued to a CVE
	// Numbering Authority (CNA) or the CVE Record was published on the CVE
	// List. Note that the Record Creation Date does not necessarily indicate
	// when this vulnerability was discovered, shared with the affected vendor,
	// publicly disclosed, or updated in CVE.
	CreatedTime int64 `json:"created_time,omitempty" parquet:"created_time,optional"`

	// Modified Time
	//
	// The Record Modified Date identifies when the CVE record was last
	// updated.
	ModifiedTime int64 `json:"modified_time,omitempty" parquet:"modified_time,optional"`

	// CVSS Score
	//
	// The CVSS object details Common Vulnerability Scoring System (CVSS)
	// scores from the advisory that are related to the vulnerability.
	CVSS []CVSS `json:"cvss,omitempty" parquet:"cvss,list"`

	// References
	//
	// A list of reference URLs with additional information about the CVE
	// Record.
	References []string `json:"references,omitempty" parquet:"references,list"`
}

// CVSS is the OCSF CVSS Score object.
//
// The Common Vulnerability Scoring System (CVSS) object provides a way to
// capture the principal characteristics of a vulnerability and produce a
// numerical score reflecting its severity.
type CVSS struct {
	// Version
	//
	// The CVSS version. For example: 3.1.
	Version string `json:"version" parquet:"version"`

	// Base Score
	//
	// The CVSS base score. For example: 9.1.
	BaseScore float64 `json:"base_score" parquet:"base_score"`

	// Severity
	//
	// The Common Vulnerability Scoring System (CVSS) Qualitative Severity
	// Rating. A textual representation of the numeric score.CVSS v2.0Low (0.0
	// – 3.9)Medium (4.0 – 6.9)High (7.0 – 10.0)CVSS v3.0None (0.0)Low
	// (0.1 - 3.9)Medium (4.0 - 6.9)High (7.0 - 8.9)Critical (9.0 - 10.0)
	Severity string `json:"severity,omitempty" parquet:"severity,optional"`

	// Vector String
	//
	// The CVSS vector string is a text representation of a set of CVSS
	// metrics. It is commonly used to record or transfer CVSS metric
	// information in a concise form. For example:
	// 3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:H.
	VectorString string `json:"vector_string,omitempty" parquet:"vector_string,optional"`
}

// Device is the OCSF Device object.
//
// The Device object represents an addressable computer system or host, which
// is typically connected to a computer network and participates in the
// transmission or processing of data within the computer network. Defined by
// D3FEND d3f:Host.
type Device struct {
	// Type ID
	//
	// The device type ID.
	TypeID int `json:"type_id" parquet:"type_id"`

	// Type
	//
	// The device type. For example: unknown, server, desktop, laptop, tablet,
	// mobile, virtual, browser, or other.
	Type string `json:"type,omitempty" parquet:"type,optional"`

	// Unique ID
	//
	// The unique identifier of the device. For example the Windows TargetSID
	// or AWS EC2 ARN.
	UID string `json:"uid,omitempty" parquet:"uid,optional"`

	// Name
	//
	// The alternate device name, ordinarily as assigned by an administrator.
	// Note: The Name could be any other string that helps to identify the
	// device, such as a phone number; for example 310-555-1234.
	Name string `json:"name,omitempty" parquet:"name,optional"`

	// Hostname
	//
	// The device hostname.
	Hostname string `json:"hostname,omitempty" parquet:"hostname,optional"`

	// Domain
	//
	// The network domain where the device resides. For example:
	// work.example.com.
	Domain string `json:"domain,omitempty" parquet:"domain,optional"`

	// Region
	//
	// The region where the virtual machine is located. For example, an AWS
	// Region.
	Region string `json:"region,omitempty" parquet:"region,optional"`

	// OS
	//
	// The endpoint operating system.
	OS *OS `json:"os,omitempty" parquet:"os,optional"`

	// Hardware Info
	//
	// The endpoint hardware information.
	HwInfo *DeviceHwInfo `json:"hw_info,omitempty" parquet:"hw_info,optional"`
}

// DeviceHwInfo is the OCSF Device Hardware Info object.
//
// The Device Hardware Information object contains details and specifications
// of the physical components that make up a device. This information provides
// an overview of the hardware capabilities, configuration, and characteristics
// of the device.
type DeviceHwInfo struct {
	// Processor Type
	//
	// The processor type. For example: x86 Family 6 Model 37 Stepping 5.
	CPUType string `json:"cpu_type,omitempty" parquet:"cpu_type,optional"`

	// CPU Information
	//
	// A list of cpu_info objects, each describing a physical CPU package
	// installed in the device. Use with cpu_count.
	//
	// Only in OCSF 1.9.0; empty otherwise.
	CPUInfoList []CPUInfo `json:"cpu_info_list,omitempty" parquet:"cpu_info_list,list"`
}

// FindingInfo is the OCSF Finding Information object.
//
// The Finding Information object describes metadata related to a security
// finding generated by a security tool or system.
type FindingInfo struct {
	// Unique ID
	//
	// The unique identifier of the reported finding.
	UID string `json:"uid" parquet:"uid"`

	// Title
	//
	// A title or a brief phrase summarizing the reported finding.
	Title string `json:"title" parquet:"title"`

	// Description
	//
	// The description of the reported finding.
	Desc string `json:"desc,omitempty" parquet:"desc,optional"`

	// Created Time
	//
	// The time when the finding was created.
	CreatedTime int64 `json:"created_time,omitempty" parquet:"created_time,optional"`

	// First Seen
	//
	// The time when the finding was first observed. e.g. The time when a
	// vulnerability was first observed. It can differ from the created_time
	// timestamp, which reflects the time this finding was created.
	FirstSeenTime int64 `json:"first_seen_time,omitempty" parquet:"first_seen_time,optional"`

	// Modified Time
	//
	// The time when the finding was last modified.
	ModifiedTime int64 `json:"modified_time,omitempty" parquet:"modified_time,optional"`

	// Product Identifier
	//
	// The unique identifier of the product that reported the finding.
	ProductUID string `json:"product_uid,omitempty" parquet:"product_uid,optional"`

	// Source URL
	//
	// The URL pointing to the source of the finding.
	SrcURL string `json:"src_url,omitempty" parquet:"src_url,optional"`

	// Types
	//
	// One or more types of the reported finding.
	Types []string `json:"types,omitempty" parquet:"types,list"`

	// Data Sources
	//
	// A list of data sources utilized in generation of the finding.
	DataSources []string `json:"data_sources,omitempty" parquet:"data_sources,list"`

	// Analytic
	//
	// The analytic technique used to analyze and derive insights from the data
	// or information that led to the finding or conclusion.
	Analytic *Analytic `json:"analytic,omitempty" parquet:"analytic,optional"`
}

// Metadata is the OCSF Metadata object.
//
// The Metadata object describes the metadata associated with the event.
// Defined by D3FEND d3f:Metadata.
type Metadata struct {
	// Version
	//
	// The version of the OCSF schema, using Semantic Versioning Specification
	// (SemVer). For example: 1.0.0. Event consumers use the version to
	// determine the available event attributes.
	Version string `json:"version" parquet:"version"`

	// Product
	//
	// The product that reported the event.
	Product Product `json:"product" parquet:"product"`

	// Logged Time
	//
	// The time when the logging system collected and logged the event.This
	// attribute is distinct from the event time in that event time typically
	// contain the time extracted from the original event. Most of the time,
	// these two times will be different.
	LoggedTime int64 `json:"logged_time,omitempty" parquet:"logged_time,optional"`

	// Profiles
	//
	// The list of profiles used to create the event. Profiles should be
	// referenced by their name attribute for core profiles, or extension/name
	// for profiles from extensions.
	Profiles []string `json:"profiles,omitempty" parquet:"profiles,list"`

	// Event Code
	//
	// The Event ID or Code that the product uses to describe the event.
	EventCode string `json:"event_code,omitempty" parquet:"event_code,optional"`

	// Labels
	//
	// The list of category labels attached to the event or specific
	// attributes. Labels are user defined tags or aliases added at
	// normalization time.For example: ["network", "connection.ip:destination",
	// "device.ip:source"]
	Labels []string `json:"labels,omitempty" parquet:"labels,list"`
}

// OS is the OCSF Operating System (OS) object.
//
// The Operating System (OS) object describes characteristics of an OS, such as
// Linux or Windows. Defined by D3FEND d3f:OperatingSystem.
type OS struct {
	// Name
	//
	// The operating system name.
	Name string `json:"name" parquet:"name"`

	// Type ID
	//
	// The type identifier of the operating system.
	TypeID int `json:"type_id" parquet:"type_id"`

	// Type
	//
	// The type of the operating system.
	Type string `json:"type,omitempty" parquet:"type,optional"`

	// Version
	//
	// The version of the OS running on the device that originated the event.
	// For example: "Windows 10", "OS X 10.7", or "iOS 9".
	Version string `json:"version,omitempty" parquet:"version,optional"`

	// OS Build
	//
	// The operating system build number.
	Build string `json:"build,omitempty" parquet:"build,optional"`
}

// Product is the OCSF Product object.
//
// The Product object describes characteristics of a software product.
type Product struct {
	// Name
	//
	// The name of the product.
	Name string `json:"name,omitempty" parquet:"name,optional"`

	// Vendor Name
	//
	// The name of the vendor of the product.
	VendorName string `json:"vendor_name" parquet:"vendor_name"`

	// Version
	//
	// The version of the product, as defined by the event source. For example:
	// 2013.1.3-beta.
	Version string `json:"version,omitempty" parquet:"version,optional"`

	// URL String
	//
	// The URL pointing towards the product.
	URLString string `json:"url_string,omitempty" parquet:"url_string,optional"`
}

// Remediation is the OCSF Remediation object.
//
// The Remediation object describes the recommended remediation steps to
// address identified issue(s).
type Remediation struct {
	// Description
	//
	// The description of the remediation strategy.
	Desc string `json:"desc" parquet:"desc"`

	// References
	//
	// A list of supporting URL/s, references that help describe the
	// remediation strategy.
	References []string `json:"references,omitempty" parquet:"references,list"`
}

// ResourceDetails is the OCSF Resource Details object.
//
// The Resource Details object describes details about resources that were
// affected by the activity/event.
type ResourceDetails struct {
	// Unique ID
	//
	// The unique identifier of the resource.
	UID string `json:"uid,omitempty" parquet:"uid,optional"`

	// Name
	//
	// The name of the resource.
	Name string `json:"name,omitempty" parquet:"name,optional"`

	// Type
	//
	// The resource type as defined by the event source.
	Type string `json:"type,omitempty" parquet:"type,optional"`

	// Labels
	//
	// The list of labels/tags associated to a resource.
	Labels []string `json:"labels,omitempty" parquet:"labels,list"`

	// Cloud Partition (OCSF cloud profile)
	//
	// The canonical cloud partition name to which the region is assigned (e.g.
	// AWS Partitions: aws, aws-cn, aws-us-gov).
	CloudPartition string `json:"cloud_partition,omitempty" parquet:"cloud_partition,optional"`

	// Region (OCSF cloud profile)
	//
	// The cloud region of the resource.
	Region string `json:"region,omitempty" parquet:"region,optional"`

	// Namespace
	//
	// The namespace is useful when similar entities exist that you need to
	// keep separate.
	Namespace string `json:"namespace,omitempty" parquet:"namespace,optional"`

	// Version
	//
	// The version of the resource. For example 1.2.3.
	Version string `json:"version,omitempty" parquet:"version,optional"`
}

// Vulnerability is the OCSF Vulnerability Details object.
//
// The vulnerability is an unintended characteristic of a computing component
// or system configuration that multiplies the risk of an adverse event or a
// loss occurring either due to accidental exposure, deliberate attack, or
// conflict with new system components.
type Vulnerability struct {
	// Title
	//
	// A title or a brief phrase summarizing the discovered vulnerability.
	Title string `json:"title,omitempty" parquet:"title,optional"`

	// Description
	//
	// The description of the vulnerability.
	Desc string `json:"desc,omitempty" parquet:"desc,optional"`

	// Severity
	//
	// The vendor assigned severity of the vulnerability.
	Severity string `json:"severity,omitempty" parquet:"severity,optional"`

	// CVE
	//
	// The Common Vulnerabilities and Exposures (CVE).
	CVE *CVE `json:"cve,omitempty" parquet:"cve,optional"`

	// Security Advisory
	//
	// Detail about the security advisory, that is used to publicly disclose
	// cybersecurity vulnerabilities by a vendor.
	//
	// Only in OCSF 1.9.0; empty otherwise.
	Advisory *Advisory `json:"advisory,omitempty" parquet:"advisory,optional"`

	// Affected Software Packages
	//
	// List of software packages identified as affected by a
	// vulnerability/vulnerabilities.
	AffectedPackages []AffectedPackage `json:"affected_packages,omitempty" parquet:"affected_packages,list"`

	// References
	//
	// A list of reference URLs with additional information about the
	// vulnerability.
	References []string `json:"references,omitempty" parquet:"references,list"`

	// Fix Availability
	//
	// Indicates if a fix is available for the reported vulnerability.
	IsFixAvailable bool `json:"is_fix_available,omitempty" parquet:"is_fix_available,optional"`

	// First Seen
	//
	// The time when the vulnerability was first observed.
	FirstSeenTime int64 `json:"first_seen_time,omitempty" parquet:"first_seen_time,optional"`

	// Last Seen
	//
	// The time when the vulnerability was most recently observed.
	LastSeenTime int64 `json:"last_seen_time,omitempty" parquet:"last_seen_time,optional"`

	// Vendor Name
	//
	// The name of the vendor that identified the vulnerability.
	VendorName string `json:"vendor_name,omitempty" parquet:"vendor_name,optional"`

	// Remediation Guidance
	//
	// The remediation recommendations on how to mitigate the identified
	// vulnerability.
	Remediation *Remediation `json:"remediation,omitempty" parquet:"remediation,optional"`
}
