AWSTemplateFormatVersion: "2010-09-09"
Resources:
  RootUsage:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: CloudTrail/DefaultLogGroup
      FilterPattern: '{ $.userIdentity.type = "Root" && $.userIdentity.invokedBy NOT EXISTS && $.eventType != "AwsServiceEvent" }'
      MetricTransformations:
        - MetricName: RootUsageMetric
          MetricNamespace: CISBenchmark
          MetricValue: "1"
