apiVersion: batch/v1
kind: Job
metadata:
  name: job-ports-hostport
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: job-ports-hostport
    spec:
      containers:
      - name: app
        image: nginx:1.25
        ports:
        - containerPort: 8080
      restartPolicy: Never
