apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-runasnonroot
  namespace: default
spec:
  schedule: '*/5 * * * *'
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: cronjob-runasnonroot
        spec:
          containers:
          - name: app
            image: nginx:1.25
            securityContext:
              runAsNonRoot: false
          restartPolicy: Never
