AWSTemplateFormatVersion: "2010-09-09"
Resources:
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-data-bucket
      LoggingConfiguration:
        DestinationBucketName: my-access-logs-bucket
        LogFilePrefix: data-bucket-logs/
