AWSTemplateFormatVersion: "2010-09-09"
Resources:
  SftpServer:
    Type: AWS::Transfer::Server
    Properties:
      Protocols:
        - SFTP
      EndpointType: VPC_ENDPOINT
      EndpointDetails:
        VpcEndpointId: vpce-0abcd1234ef567890
      IdentityProviderType: SERVICE_MANAGED
