AWSTemplateFormatVersion: "2010-09-09"
Resources:
  ConsoleSignInFailures:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: /aws/cloudtrail/logs
      FilterPattern: '{ ($.eventName = ConsoleLogin) && ($.additionalEventData.MFAUsed != Yes) }'
      MetricTransformations:
        - MetricName: ConsoleSignInFailures
          MetricNamespace: CISBenchmark
          MetricValue: "1"
