apiVersion: v1
kind: Pod
metadata:
  name: pod-serviceaccount
  namespace: default
  labels:
    app: pod-serviceaccount
spec:
  containers:
  - name: app
    image: nginx:1.25
  serviceAccountName: myapp-sa
