AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyWorkGroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      Name: my-workgroup
      WorkGroupConfiguration:
        EnforceWorkGroupConfiguration: true
        ResultConfiguration:
          OutputLocation: s3://my-athena-results/
