apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-hostnetwork
  namespace: default
spec:
  selector:
    matchLabels:
      app: deployment-hostnetwork
  template:
    metadata:
      labels:
        app: deployment-hostnetwork
    spec:
      containers:
      - name: app
        image: nginx:1.25
      hostNetwork: true
  replicas: 1
