# Copyright Mondoo, Inc. 2026
# SPDX-License-Identifier: BUSL-1.1
# aliyun (Alibaba Cloud) CLI validation.
#
# The aliyun CLI has no local completion tree to walk, so unlike the doctl /
# kubectl validators this one reads a checked-in command database
# (cmd_data/alicloud_commands.json, regenerated by dump_alicloud_commands.py)
# sourced from Alibaba Cloud's public OpenAPI metadata plus the aliyun-cli oss
# source. Three command shapes are validated:
#
#   RPC products   aliyun <product> <ApiAction> --<Param> <value>
#                  Action must be a real API of the product; each --Flag must be
#                  a parameter of that action (including nested object/array
#                  property names, which the CLI accepts as flat flags) or a
#                  global aliyun flag.
#   ROA products   aliyun <product> <HTTP-METHOD> <path> ...   (e.g. cs)
#                  The "action" is an HTTP verb; the path/params grammar differs,
#                  so only product + method are checked.
#   oss (ossutil)  aliyun oss <subcommand> ...
#                  oss is an embedded ossutil, not an OpenAPI product; the
#                  subcommand must be a real ossutil command. Its flag grammar
#                  is ossutil-specific and not checked here.

import json
import shlex
import sys

from .common import (
    FAILURES,
    SCRIPT_DIR,
    extract_bash_blocks,
    policy_relpath,
    split_commands,
    truncate_cmd,
)

ALICLOUD_POLICY_FILE = SCRIPT_DIR / ".." / "mondoo-alibaba-security.mql.yaml"
CMD_DATA_FILE = SCRIPT_DIR / "cmd_data" / "alicloud_commands.json"

# aliyun CLI global flags — valid regardless of product/action. Matched
# case-insensitively. API parameters are matched case-sensitively (they are
# PascalCase and collide with nothing here).
GLOBAL_FLAGS = {
    "access-key-id", "access-key-secret", "sts-token", "mode", "profile",
    "region", "endpoint", "ram-role-name", "ram-role-arn", "role-session-name",
    "oidc-provider-arn", "oidc-token-file", "key-pair-name", "private-key",
    "expiration", "output", "cols", "rows", "filter", "force", "version",
    "secure", "quiet", "config-path", "retry-count", "retry-timeout",
    "read-timeout", "connect-timeout", "skip-secure-verify", "header", "body",
    "content-type", "accept", "pager", "all-pages", "page-size", "page-number",
    "tolerant", "roa", "method", "path", "help",
}

ROA_METHODS = {"GET", "POST", "PUT", "DELETE", "PATCH", "HEAD"}


def load_db() -> dict:
    if not CMD_DATA_FILE.exists():
        print(
            f"Error: {CMD_DATA_FILE} not found.\n"
            "Regenerate it with:\n"
            f"  python3 {SCRIPT_DIR / 'dump_alicloud_commands.py'}",
            file=sys.stderr,
        )
        sys.exit(1)
    return json.loads(CMD_DATA_FILE.read_text())


def parse_flags(tokens: list[str]) -> list[str]:
    flags = []
    for tok in tokens:
        if tok.startswith("--"):
            flags.append(tok.split("=", 1)[0][2:])
    return flags


def validate_command(cmd: str, db: dict) -> tuple[bool, list[str]]:
    """Validate one `aliyun ...` command. Returns (is_valid, errors)."""
    try:
        tokens = shlex.split(cmd)
    except ValueError:
        tokens = cmd.split()

    if len(tokens) < 3 or tokens[0] != "aliyun":
        # Too short to carry a product+action; nothing to check.
        return True, []

    product, action = tokens[1], tokens[2]
    products = db["products"]

    # oss is an embedded ossutil, not an OpenAPI RPC product.
    if product == "oss":
        if action in db["oss_subcommands"]:
            return True, []
        return False, [
            f"'aliyun oss {action}' is not a valid ossutil subcommand "
            "(oss is not an OpenAPI product; use e.g. bucket-encryption, "
            "logging, bucket-versioning, bucket-policy, set-acl)"
        ]

    if product not in products:
        return False, [f"unknown aliyun product '{product}'"]

    entry = products[product]
    actions = entry["actions"]

    # ROA products (e.g. cs) are called as `aliyun <product> <METHOD> <path>`.
    if entry["style"] == "ROA":
        if action in ROA_METHODS or action in actions:
            return True, []
        return False, [
            f"'aliyun {product} {action}' — {product} is a RESTful (ROA) product; "
            f"expected an HTTP method ({', '.join(sorted(ROA_METHODS))}) or a known operation"
        ]

    # RPC products: action must be a real API, flags must be its parameters.
    if action not in actions:
        return False, [f"unknown API action 'aliyun {product} {action}'"]

    valid_params = set(actions[action])
    errors = []
    for flag in parse_flags(tokens):
        if flag_ok(flag, valid_params):
            continue
        errors.append(f"unknown flag '--{flag}' for 'aliyun {product} {action}'")
    return len(errors) == 0, errors


def flag_ok(flag: str, valid_params: set) -> bool:
    """A flag is valid if it is a global flag, a top-level parameter, or a
    nested parameter path. The aliyun CLI addresses nested object/array
    parameters with dotted, index-bearing flags (--Listen.TLSVersion,
    --Permissions.1.IpProtocol); we accept the flag when its final non-index
    segment is a known parameter name, which is lenient but matches the CLI
    grammar without modelling exact nesting."""
    if flag in valid_params:
        return True
    if flag.lower() in GLOBAL_FLAGS:
        return True
    segments = [s for s in flag.split(".") if not s.isdigit()]
    return bool(segments) and segments[-1] in valid_params


def validate_alicloud() -> tuple[int, int]:
    """Validate aliyun CLI commands in the Alibaba policy. Returns (pass, fail)."""
    if not ALICLOUD_POLICY_FILE.exists():
        print(f"Error: Policy file not found: {ALICLOUD_POLICY_FILE}", file=sys.stderr)
        sys.exit(1)

    db = load_db()
    content = ALICLOUD_POLICY_FILE.read_text()
    # Greenfield policy with no unvalidated-audit backlog, so audit blocks are
    # validated too — a wrong audit command misleads an auditor just like a
    # wrong remediation.
    blocks = extract_bash_blocks(content, include_audit=True)

    relpath = policy_relpath(ALICLOUD_POLICY_FILE)
    pass_count = 0
    fail_count = 0

    for block_text, block_line, uid in blocks:
        for cmd, line_num in split_commands(block_text, "aliyun", block_line):
            is_valid, errors = validate_command(cmd, db)
            if is_valid:
                print(f"[PASS] {uid}")
                print(f"       {truncate_cmd(cmd)}")
                pass_count += 1
            else:
                print(f"[FAIL] {uid}")
                print(f"       {truncate_cmd(cmd)}")
                for error in errors:
                    print(f"       {error}")
                fail_count += 1
                FAILURES.append({
                    "file": relpath,
                    "line": line_num,
                    "uid": uid,
                    "command": truncate_cmd(cmd),
                    "errors": errors,
                    "cloud": "alicloud",
                })

    return pass_count, fail_count
