apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset-hostnetwork
  namespace: default
spec:
  selector:
    matchLabels:
      app: daemonset-hostnetwork
  template:
    metadata:
      labels:
        app: daemonset-hostnetwork
    spec:
      containers:
      - name: app
        image: nginx:1.25
      hostNetwork: true
