AWSTemplateFormatVersion: "2010-09-09"
Resources:
  AppEnv:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: my-app
      EnvironmentName: my-app-prod
      SolutionStackName: "64bit Amazon Linux 2 v3.5.9 running Docker"
      OptionSettings:
        - Namespace: aws:elasticbeanstalk:healthreporting:system
          OptionName: SystemType
          Value: basic
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: InstanceType
          Value: t3.small
