# Sample configuration for Mondoo Platform
#
# To setup cnspec command line with Mondoo Platform:
# https://mondoo.com/docs/tutorials/mondoo/account-setup/
#

api_endpoint: https://us.api.mondoo.app
mrn: //agents.api.mondoo.app/spaces/yourspace/agents/agentid
space_mrn: //captain.api.mondoo.app/spaces/yourspace
certificate: |
  -----BEGIN CERTIFICATE-----
  MIICejCCAgCgAwIBAgIQPJbAYJt7dWfKYUczMIczYzAKBggqhkjOPQQDAzBJMUcw
  ...
  vwslpvFVlcqz7cLJAjAGliwok123Wtbfqsflx2Y0jI7piYq0doS3LERwk3o3dvLP
  tzc9MCERV1GLqyJ8YTI=
  -----END CERTIFICATE-----
private_key: |
  -----BEGIN PRIVATE KEY-----
  MIG2AgEAMBAGByqGSM49AgEGBSuBBAAiBIGeMIGbAgEBBDAueHZkyYbyeGpdcI1V
  ...
  LaCIG0tdW8WL1rUH9WaxWguU0mAMIbY3muEcwYvcTcJH7NX7hiLYN6I=
  -----END PRIVATE KEY-----
