AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyWindow:
    Type: AWS::SSM::MaintenanceWindow
    Properties:
      Name: my-maintenance-window
      Schedule: "cron(0 2 ? * MON *)"
      Duration: 2
      Cutoff: 1
      AllowUnassociatedTargets: false
