AWSTemplateFormatVersion: "2010-09-09"
Resources:
  ServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: PostgreSQL security group with no inbound rules
      VpcId: vpc-0abc1234def567890
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
