AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyInstance:
    Type: AWS::Neptune::DBInstance
    Properties:
      DBInstanceClass: db.r5.large
      DBClusterIdentifier: my-neptune-cluster
      AutoMinorVersionUpgrade: true
