package yacit

import (
	"fmt"
	"io"
	"os"
	"reflect"
	"strings"
	"unicode"
)

const prefix = `
// Code generated by yac-it. DO NOT EDIT.
//
// Configure yac-it for things you want to auto-generate and extend generated
// objects in a separate file please.

import (
	"gopkg.in/yaml.v3"
)

type FileContext struct {
	Line int
	Column int
}

`

func New(conf YacItConfig) *YacIt {
	res := &YacIt{
		types:           map[string]string{},
		io:              os.Stderr,
		customUnmarshal: map[string]struct{}{},
		pkg:             conf.Package,
	}

	for _, v := range conf.CustomUnmarshal {
		res.customUnmarshal[v] = struct{}{}
	}

	return res
}

type YacItConfig struct {
	CustomUnmarshal []string
	Package         string
}

type YacIt struct {
	types           map[string]string
	io              io.Writer
	customUnmarshal map[string]struct{}
	pkg             string
}

func (t *YacIt) Add(typ interface{}) {
	t.createStruct(reflect.TypeOf(typ).Elem())
}

func (t *YacIt) String() string {
	var res strings.Builder

	if t.pkg != "" {
		res.WriteString("package " + t.pkg + "\n")
	}

	res.WriteString(prefix)

	for _, v := range t.types {
		res.WriteString(v)
		res.WriteByte('\n')
	}

	return res.String()
}

func (t *YacIt) createStruct(typ reflect.Type) {
	name := typ.Name()

	if _, ok := t.types[name]; ok {
		return
	}

	var res strings.Builder
	res.WriteString("type " + name + " struct {\n")

	nuFields := make([]reflect.StructField, 0)
	for i := 0; i < typ.NumField(); i++ {
		cur := typ.Field(i)

		// TODO: limited to ascii right now, no utf8 runes
		if unicode.IsLower(rune(cur.Name[0])) {
			continue
		}

		nuFields = append(nuFields, cur)
		nuTag := addYamlTag(cur.Tag)
		nuFields[len(nuFields)-1].Tag = (nuTag)
	}

	for i := range nuFields {
		field := nuFields[i]

		res.WriteByte('\t')
		res.WriteString(field.Name)
		res.WriteByte(' ')
		res.WriteString(printType(field.Type))
		res.WriteByte(' ')
		res.WriteByte('`')
		res.WriteString(string(field.Tag))
		res.WriteByte('`')
		res.WriteByte('\n')
	}

	res.WriteString("\tFileContext FileContext `json:\"-\" yaml:\"-\"`\n")
	res.WriteString("}\n")

	if _, isCustom := t.customUnmarshal[name]; !isCustom {
		res.WriteString(fmt.Sprintf(`
func (x *%s) UnmarshalYAML(node *yaml.Node) error {
	// prevent recursive calls into UnmarshalYAML with a placeholder type
	type tmp %s
	err := node.Decode((*tmp)(x))
	if err != nil {
		return err
	}

	x.FileContext.Column = node.Column
	x.FileContext.Line = node.Line
	return nil
}
`, name, name))
	} else {
		res.WriteString(fmt.Sprintf(`
func (x *%s) addFileContext(node *yaml.Node) {
	x.FileContext.Column = node.Column
	x.FileContext.Line = node.Line
}
`, name))
	}

	t.types[name] = res.String()

	for i := range nuFields {
		typ := baseType(nuFields[i].Type)
		switch typ.Kind() {
		case reflect.Struct:
			t.io.Write([]byte("process type: " + typ.Name() + "\n"))
			t.createStruct(typ)
		}
	}
}

// unlike typ.String() we strip the namespace from all types
func printType(typ reflect.Type) string {
	switch typ.Kind() {
	case reflect.Slice:
		return "[]" + printType(typ.Elem())
	case reflect.Pointer:
		return "*" + printType(typ.Elem())
	case reflect.Map:
		return "map[" + typ.Key().String() + "]" + printType(typ.Elem())
	case reflect.Array:
		// TODO: technically we need the number here...
		return "[]" + printType(typ.Elem())
	case reflect.Struct:
		return typ.Name()
	default:
		return typ.String()
	}
}

func baseType(typ reflect.Type) reflect.Type {
	for {
		switch typ.Kind() {
		case reflect.Slice, reflect.Pointer, reflect.Map, reflect.Array:
			typ = typ.Elem()
		default:
			return typ
		}
	}
}

func addYamlTag(s reflect.StructTag) reflect.StructTag {
	j := s.Get("json")
	if j == "" {
		return s
	}

	res := string(s) + " yaml:" + fmt.Sprintf("%#v", j)
	return reflect.StructTag(res)
}
