AWSTemplateFormatVersion: "2010-09-09"
Resources:
  SiteCert:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: example.com
      ValidationMethod: DNS
      KeyAlgorithm: EC_prime256v1
