AWSTemplateFormatVersion: "2010-09-09"
Resources:
  Sub:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: arn:aws:sns:us-east-1:123456789012:my-topic
      Protocol: sqs
      Endpoint: arn:aws:sqs:us-east-1:123456789012:my-queue
