AWSTemplateFormatVersion: "2010-09-09"
Resources:
  GetItemsRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: "GET /items"
      AuthorizationType: AWS_IAM
      Target: !Sub "integrations/${MyIntegration}"
