AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyImageBuilder:
    Type: AWS::AppStream::ImageBuilder
    Properties:
      Name: my-image-builder
      InstanceType: stream.standard.medium
      ImageName: AppStream-WinServer2019-06-01-2023
      EnableDefaultInternetAccess: false
