AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      Type: container
      JobDefinitionName: my-job
      ContainerProperties:
        Image: registry.example.com/team/my-app:1.2.3
        Vcpus: 1
        Memory: 512
