apiVersion: v1
kind: Pod
metadata:
  name: pod-readonlyrootfilesystem
  namespace: default
  labels:
    app: pod-readonlyrootfilesystem
spec:
  containers:
  - name: app
    image: nginx:1.25
    securityContext:
      readOnlyRootFilesystem: true
