AWSTemplateFormatVersion: "2010-09-09"
Resources:
  AppRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: my-app
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicPull
            Effect: Allow
            Principal: "*"
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
