apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-capability-sys-admin
  namespace: default
spec:
  selector:
    matchLabels:
      app: replicaset-capability-sys-admin
  template:
    metadata:
      labels:
        app: replicaset-capability-sys-admin
    spec:
      containers:
      - name: app
        image: nginx:1.25
  replicas: 1
