AWSTemplateFormatVersion: "2010-09-09"
Resources:
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: my-data-bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: DenyInsecureTransport
            Effect: Deny
            Principal: "*"
            Action: s3:*
            Resource: arn:aws:s3:::my-data-bucket/*
            Condition:
              Bool:
                aws:SecureTransport: "false"
