AWSTemplateFormatVersion: "2010-09-09"
Resources:
  AnalyticsWorkGroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      Name: analytics
      WorkGroupConfiguration:
        EnforceWorkGroupConfiguration: true
        EnableMinimumEncryptionConfiguration: true
        ResultConfiguration:
          OutputLocation: s3://example-athena-results/analytics/
          EncryptionConfiguration:
            EncryptionOption: SSE_KMS
            KmsKey: arn:aws:kms:us-east-1:123456789012:key/1234abcd-12ab-34cd-56ef-1234567890ab
