apiVersion: v1
kind: Pod
metadata:
  name: pod-containerd-socket
  namespace: default
  labels:
    app: pod-containerd-socket
spec:
  containers:
  - name: app
    image: nginx:1.25
    volumeMounts:
    - name: sock
      mountPath: /run/containerd/containerd.sock
  volumes:
  - name: sock
    hostPath:
      path: /run/containerd/containerd.sock
