AWSTemplateFormatVersion: "2010-09-09"
Resources:
  ConfigChanges:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: CloudTrail/DefaultLogGroup
      FilterPattern: '{ ($.eventSource = config.amazonaws.com) && (($.eventName = StopConfigurationRecorder) || ($.eventName = DeleteDeliveryChannel) || ($.eventName = PutDeliveryChannel) || ($.eventName = PutConfigurationRecorder)) }'
      MetricTransformations:
        - MetricName: ConfigChangesMetric
          MetricNamespace: CISBenchmark
          MetricValue: "1"
