AWSTemplateFormatVersion: "2010-09-09"
Resources:
  Share:
    Type: AWS::RAM::ResourceShare
    Properties:
      Name: internal-share
      AllowExternalPrincipals: false
      ResourceArns:
        - arn:aws:ec2:us-east-1:123456789012:subnet/subnet-0abc1234
