AWSTemplateFormatVersion: "2010-09-09"
Resources:
  GatewayChanges:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: CloudTrail/DefaultLogGroup
      FilterPattern: '{ ($.eventName = CreateCustomerGateway) || ($.eventName = DeleteCustomerGateway) || ($.eventName = AttachInternetGateway) || ($.eventName = CreateInternetGateway) || ($.eventName = DeleteInternetGateway) }'
      MetricTransformations:
        - MetricName: GatewayChangesMetric
          MetricNamespace: CISBenchmark
          MetricValue: "1"
