AWSTemplateFormatVersion: "2010-09-09"
Resources:
  CloudTrailConfig:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: CloudTrail/DefaultLogGroup
      FilterPattern: '{ ($.eventName = CreateTrail) || ($.eventName = UpdateTrail) || ($.eventName = DeleteTrail) || ($.eventName = StartLogging) || ($.eventName = StopLogging) }'
      MetricTransformations:
        - MetricName: CloudTrailConfigMetric
          MetricNamespace: CISBenchmark
          MetricValue: "1"
