AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyAggregator:
    Type: AWS::Config::ConfigurationAggregator
    Properties:
      ConfigurationAggregatorName: my-aggregator
      AccountAggregationSources:
        - AccountIds:
            - "123456789012"
          AllAwsRegions: true
