apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-privilegedcontainer
  namespace: default
spec:
  selector:
    matchLabels:
      app: replicaset-privilegedcontainer
  template:
    metadata:
      labels:
        app: replicaset-privilegedcontainer
    spec:
      containers:
      - name: app
        image: nginx:1.25
        securityContext:
          privileged: true
  replicas: 1
