AWSTemplateFormatVersion: "2010-09-09"
Resources:
  RootCA:
    Type: AWS::ACMPCA::CertificateAuthority
    Properties:
      Type: ROOT
      KeyAlgorithm: EC_prime256v1
      SigningAlgorithm: SHA384WITHECDSA
      Subject:
        Organization: Example Corp
        CommonName: Example Root CA
