apiVersion: v1
kind: Pod
metadata:
  name: pod-docker-socket
  namespace: default
  labels:
    app: pod-docker-socket
spec:
  containers:
  - name: app
    image: nginx:1.25
    volumeMounts:
    - name: sock
      mountPath: /var/run/docker.sock
  volumes:
  - name: sock
    hostPath:
      path: /var/run/docker.sock
