apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-hostnetwork
  namespace: default
spec:
  selector:
    matchLabels:
      app: statefulset-hostnetwork
  template:
    metadata:
      labels:
        app: statefulset-hostnetwork
    spec:
      containers:
      - name: app
        image: nginx:1.25
      hostNetwork: true
  replicas: 1
  serviceName: statefulset-hostnetwork
