AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyCluster:
    Type: AWS::MSK::Cluster
    Properties:
      ClusterName: my-msk
      KafkaVersion: 3.5.1
      NumberOfBrokerNodes: 3
      BrokerNodeGroupInfo:
        InstanceType: kafka.m5.large
        ClientSubnets:
          - subnet-0123456789abcdef0
          - subnet-0123456789abcdef1
      LoggingInfo:
        BrokerLogs:
          CloudWatchLogs:
            Enabled: true
            LogGroup: /aws/msk/my-cluster
