AWSTemplateFormatVersion: "2010-09-09"
Resources:
  AppCache:
    Type: AWS::MemoryDB::Cluster
    Properties:
      ClusterName: app-cache
      NodeType: db.r6g.large
      ACLName: app-acl
      AutoMinorVersionUpgrade: false
