apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset-capability-drop-all
  namespace: default
spec:
  selector:
    matchLabels:
      app: daemonset-capability-drop-all
  template:
    metadata:
      labels:
        app: daemonset-capability-drop-all
    spec:
      containers:
      - name: app
        image: nginx:1.25
        securityContext:
          capabilities:
            drop:
            - ALL
