AWSTemplateFormatVersion: "2010-09-09"
Resources:
  RouteTableChangesMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: /aws/cloudtrail/logs
      FilterPattern: '{ ($.eventName = CreateRoute) || ($.eventName = CreateRouteTable) || ($.eventName = ReplaceRoute) || ($.eventName = ReplaceRouteTableAssociation) || ($.eventName = DeleteRouteTable) || ($.eventName = DeleteRoute) || ($.eventName = DisassociateRouteTable) }'
      MetricTransformations:
        - MetricName: RouteTableChanges
          MetricNamespace: CISBenchmark
          MetricValue: "1"
