AWSTemplateFormatVersion: "2010-09-09"
Resources:
  Cluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-postgresql
      EngineVersion: "15.4"
      MasterUsername: admin
      ManageMasterUserPassword: true
      StorageEncrypted: true
