AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyDomain:
    Type: AWS::OpenSearchService::Domain
    Properties:
      DomainName: my-domain
      LogPublishingOptions:
        AUDIT_LOGS:
          CloudWatchLogsLogGroupArn: arn:aws:logs:us-east-1:123456789012:log-group:/aws/opensearch/audit
          Enabled: true
