apiVersion: v1
kind: Pod
metadata:
  name: pod-capability-sys-admin
  namespace: default
  labels:
    app: pod-capability-sys-admin
spec:
  containers:
  - name: app
    image: nginx:1.25
    securityContext:
      capabilities:
        add:
        - SYS_ADMIN
