apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-containerd-socket
  namespace: default
spec:
  selector:
    matchLabels:
      app: replicaset-containerd-socket
  template:
    metadata:
      labels:
        app: replicaset-containerd-socket
    spec:
      containers:
      - name: app
        image: nginx:1.25
        volumeMounts:
        - name: sock
          mountPath: /run/containerd/containerd.sock
      volumes:
      - name: sock
        hostPath:
          path: /run/containerd/containerd.sock
  replicas: 1
