AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: my-custom-origin
          ViewerProtocolPolicy: redirect-to-https
        Origins:
          - Id: my-custom-origin
            DomainName: api.example.com
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
