AWSTemplateFormatVersion: "2010-09-09"
Resources:
  EMRSecurityConfig:
    Type: AWS::EMR::SecurityConfiguration
    Properties:
      Name: emr-security-config
      SecurityConfiguration:
        EncryptionConfiguration:
          EnableInTransitEncryption: false
          EnableAtRestEncryption: true
          AtRestEncryptionConfiguration:
            S3EncryptionConfiguration:
              EncryptionMode: SSE-S3
