#!/usr/bin/env python3
# Copyright Mondoo, Inc. 2024, 2026
# SPDX-License-Identifier: BUSL-1.1
#
# Regenerates data/proxmox_api.json, the grammar behind `pvesh` validation.
#
# Proxmox VE defines its whole API in JSON Schema and generates both the API
# viewer and the CLI tools from it. pve-docs publishes that schema as
# api-viewer/apidata.js — a JavaScript file whose body is a JSON array, pinned
# here to the commit that produced it.
#
# `pvesh` takes API paths directly (`pvesh set /cluster/firewall/options
# --enable 1`), so this schema is the exact oracle for it: the path, the
# method, and the option names are all right there. The other Proxmox CLIs
# (pct, qm, pveum, pvenode, pvesm, pvecm) are generated from the same schema,
# but the subcommand-to-API-path mapping lives in the Perl sources and is not
# published in any machine-readable form, so they are out of scope. See the
# note in commands/proxmox.py.
#
# The published file is 4.2 MB, nearly all of it prose descriptions and return
# schemas the validator never reads. What is kept is the path, its methods,
# each method's parameter names, and which of them are required — 122 KB.
#
# Usage:
#   python3 content/validation/upstream/dump/proxmox.py

import json
import re
import sys
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))  # content/validation
from paths import DATA_DIR  # noqa: E402

# pve-docs commit that last touched api-viewer/apidata.js. Pinned rather than
# tracked from master so a regeneration is reproducible: re-running this script
# without changing the pin must produce the same bytes, or the weekly refresh
# job opens a pull request every time it runs.
PVE_DOCS_SHA = "4e7ff22c70eb35c63e65b0ba65c98980cb4d7bf5"

SOURCE = (
    "https://raw.githubusercontent.com/proxmox/pve-docs/"
    f"{PVE_DOCS_SHA}/api-viewer/apidata.js"
)

OUTPUT = DATA_DIR / "proxmox_api.json"


def fetch(url: str) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": "cnspec-validation"})
    with urllib.request.urlopen(req, timeout=120) as resp:
        return resp.read().decode("utf-8")


# The one statement in apidata.js: `const apiSchema = [ ... ];`. Anchored on the
# assignment rather than sliced between the first `[` and the last `]`, so a
# preamble that ever gains a bracket — a licence header, a comment — fails here
# with a message naming the file instead of somewhere inside json.loads.
_API_SCHEMA_ASSIGNMENT = re.compile(r"apiSchema\s*=\s*(\[.*\])\s*;", re.DOTALL)


def parse_apidata(text: str) -> list:
    """Extract the JSON array out of `const apiSchema = [...];`."""
    m = _API_SCHEMA_ASSIGNMENT.search(text)
    if not m:
        raise ValueError(
            "apidata.js does not contain an `apiSchema = [...];` assignment. "
            "Upstream changed the file's shape; update _API_SCHEMA_ASSIGNMENT."
        )
    return json.loads(m.group(1))


def flatten(tree: list) -> dict:
    """Map every API path to its node, depth-first."""
    nodes = {}

    def walk(children):
        for node in children:
            path = node.get("path")
            if path:
                nodes[path] = node
            walk(node.get("children") or [])

    walk(tree)
    return nodes


def compact(nodes: dict) -> dict:
    """Keep only what the validator reads: methods, parameters, required."""
    out = {}
    for path, node in nodes.items():
        methods = {}
        for method, info in (node.get("info") or {}).items():
            props = (info.get("parameters") or {}).get("properties") or {}
            methods[method] = {
                "params": sorted(props),
                # `optional` is 0 or absent for a required parameter.
                "required": sorted(k for k, v in props.items() if not v.get("optional")),
            }
        if methods:
            out[path] = methods
    return out


def main() -> None:
    print(f"Fetching {SOURCE}")
    tree = parse_apidata(fetch(SOURCE))
    nodes = flatten(tree)
    paths = compact(nodes)

    if len(paths) < 300:
        print(
            f"Error: only {len(paths)} API paths parsed, expected several hundred. "
            "Refusing to write a grammar smaller than the policy needs.",
            file=sys.stderr,
        )
        sys.exit(1)

    payload = {
        "_meta": {
            "source": SOURCE,
            "pin": PVE_DOCS_SHA,
            "note": (
                "Generated by content/validation/upstream/dump/proxmox.py. "
                "Never hand-edit; bump PVE_DOCS_SHA and re-run."
            ),
        },
        "paths": paths,
    }
    OUTPUT.write_text(json.dumps(payload, indent=1, sort_keys=True) + "\n")
    methods = sum(len(m) for m in paths.values())
    print(f"Wrote {OUTPUT} — {len(paths)} paths, {methods} methods")


if __name__ == "__main__":
    main()
