name: Policy File Update Trigger (Push)

# This block allows the workflow to be triggered by a manual run (UI, CLI, API)
on:
  workflow_dispatch:
    inputs:
      # Define inputs if the manual run needs to specify parameters
      # Although this is optional, it's good practice to provide inputs for manual triggers.
      # Since your job call uses inputs from the push event, you might need dummy values.
      manual_actor:
        description: 'The actor for the manual run'
        required: false
        default: ${{ github.actor }}
      manual_ref:
        description: 'The branch reference for the manual run (e.g., refs/heads/main)'
        required: false
        default: ${{ github.ref }}

  # Keep the original push trigger
  push:
    branches:
      - main
    paths:
      - 'content/*.mql.yaml'
      - 'content/vulnerabilities/*.mql.yaml'

jobs:
  trigger_policy_update:
    name: Call Policy Update Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Call Policy Update Script Executor
        uses: mondoohq/server/.github/workflows/update-policies.yaml@main
        with:
          # Use a conditional expression (coalescing) to decide which value to pass:
          # If the event is workflow_dispatch, use the manual input.
          # If the event is push, use the push context.
          source_repository: ${{ github.repository }}
          source_ref: ${{ github.event_name == 'workflow_dispatch' && inputs.manual_ref || github.ref }}
          actor: ${{ github.event_name == 'workflow_dispatch' && inputs.manual_actor || github.actor }}
