name: Policy File Update Trigger (Push)

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - philip/ci-job-bump-policies
    paths:
      - 'content/*.mql.yaml'
      - 'content/vulnerabilities/*.mql.yaml'

jobs:
  call-my-workflow:
    uses: mondoohq/server/.github/workflows/update-policies.yaml@a9d66ff0dc7d62257f1c3e89307b1ac7a3d53495
    with:
      source_repository: ${{ github.repository }}
      source_ref: ${{ github.ref }}
      actor: ${{ github.actor }}
    secrets: inherit
