name: Policy File Update Trigger (Push)

on:
  workflow_dispatch:
    inputs:
      manual_actor:
        description: 'The actor for the manual run'
        required: false
        default: ${{ github.actor }}
      manual_ref:
        description: 'The branch reference for the manual run (e.g., refs/heads/main)'
        required: false
        default: ${{ github.ref }}

  push:
    branches:
      - main
      - philip/ci-job-bump-policies
    paths:
      - 'content/*.mql.yaml'
      - 'content/vulnerabilities/*.mql.yaml'

jobs:
  trigger_policy_update:
    name: Call Policy Update Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Call Policy Update Script Executor
        uses: mondoohq/server/.github/workflows/update-policies.yaml@main
        with:
          source_repository: ${{ github.repository }}
          source_ref: ${{ github.event_name == 'workflow_dispatch' && inputs.manual_ref || github.ref }}
          actor: ${{ github.event_name == 'workflow_dispatch' && inputs.manual_actor || github.actor }}
