---
name: Link Checking

"on":
  pull_request:
  push:
    branches: [main]

concurrency:
  group: link-check-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read

jobs:
  md-links:
    name: Run markdown link check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Check links
        uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 # v2.9.0
        with:
          lycheeVersion: "v0.22.0"
          args: --config lychee.toml './**/*.md'
