name: Benchmark

# Run on push to main to update the baseline, and on pull requests to check for regressions.
on:
  push:
    branches:
      - main
    paths:
      - '**.go'
      - '**.mod'
      - 'go.sum'
      - .github/workflows/main-benchmark.yml
  pull_request:
    paths:
      - '**.go'
      - '**.mod'
      - 'go.sum'
      - .github/workflows/main-benchmark.yml

permissions:
  # Required to push to the gh-pages branch
  contents: write
  # Required to comment on pull requests
  pull-requests: write
  # Required to deploy GitHub Pages (if you use it for charts)
  deployments: write

jobs:
  go-bench:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Import environment variables from file
        run: cat ".github/env" >> $GITHUB_ENV
        
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=${{ env.golang-version }}"
          
      - name: Run benchmark
        run: make benchmark/go | tee benchmark.txt

      - name: Cleanup benchmark file
        run: sed -i -n '/goos:/,$p' benchmark.txt

      # This is the key change. We now use the recommended gh-pages strategy.
      - name: Store benchmark result and compare
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'go'
          output-file-path: benchmark.txt
          
          # Use a dedicated branch to store historical data.
          gh-pages-branch: gh-pages
          
          # On pushes to 'main', this will update the baseline data.
          # On pull requests, it will fetch the baseline from 'main' to compare against.
          auto-push: true
                    
          # Fail the workflow if a regression is detected.
          fail-on-alert: true
          
          # Leave a comment on the PR if a regression is detected.
          # This only runs on pull_request events.
          comment-on-alert: true
          
          # Required for commenting on PRs and pushing to the gh-pages branch.
          github-token: ${{ secrets.GITHUB_TOKEN }}