name: Trigger installer release

on:
  workflow_run:
    workflows: ["goreleaser"]
    types:
      - completed

jobs:
  release-installer:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger installer release
        env:
          GH_TOKEN: ${{ secrets.REPO_API_TOKEN }}
        run: gh workflow run release_mondoo_pkgs.yaml --repo "mondoohq/installer" --field version=${{ github.ref_name }}
