AWSTemplateFormatVersion: "2010-09-09"
Resources:
  SearchDomain:
    Type: AWS::OpenSearchService::Domain
    Properties:
      DomainName: prod-search
      EngineVersion: OpenSearch_2.11
      DomainEndpointOptions:
        EnforceHTTPS: true
        TLSSecurityPolicy: Policy-Min-TLS-1-2-PFS-2023-10
