AWSTemplateFormatVersion: "2010-09-09"
Resources:
  AppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Wide-open IPv6 security group
      VpcId: vpc-0abcd1234ef567890
      SecurityGroupIngress:
        - IpProtocol: -1
          CidrIpv6: ::/0
