AWSTemplateFormatVersion: "2010-09-09"
Resources:
  NotebookInstance:
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      InstanceType: ml.t3.medium
      RoleArn: arn:aws:iam::123456789012:role/SageMakerRole
      KmsKeyId: arn:aws:kms:us-east-1:123456789012:key/abcd-1234-ef56-7890
      DirectInternetAccess: Disabled
      RootAccess: Disabled
