apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-crio-socket
  namespace: default
spec:
  selector:
    matchLabels:
      app: statefulset-crio-socket
  template:
    metadata:
      labels:
        app: statefulset-crio-socket
    spec:
      containers:
      - name: app
        image: nginx:1.25
        volumeMounts:
        - name: sock
          mountPath: /var/run/crio/crio.sock
      volumes:
      - name: sock
        hostPath:
          path: /var/run/crio/crio.sock
  replicas: 1
  serviceName: statefulset-crio-socket
