AWSTemplateFormatVersion: "2010-09-09"
Resources:
  TopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref MyTopic
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicPublish
            Effect: Allow
            Principal: "*"
            Action: sns:Publish
            Resource: "*"
